### ISSUE TITLE
The link (https://atom.io/roadmap?app) from Atom 1.6.1 to the roadmap does no longer work

### ISSUE THREAD

**Issue by doberkofler** [atom/atom#11332]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Starting (at least) with Atom 1.6.1 the menu option Help > Roadmap (https://atom.io/roadmap?app) shows a 404 error page.

### Steps to Reproduce

1. Use Menu "Help > Roadmap"

### Versions

atom --version
1.6.1

apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.3
git 2.6.0.windows.1
visual studio 2013

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.7.0.

**Comment by kirtangajjar** [comment]
It's dead again

**Comment by kirtangajjar** [comment]
@50Wliu

**Comment by 50Wliu** [comment]
The "fix" was that the Help > Roadmap menu link was removed.  The Atom team is not planning on reinstating the roadmap.

**Comment by doberkofler** [comment]
No longer having an official roadmap is a major step in the wrong direction of this project. I miss it very much!

**Comment by 50Wliu** [comment]
https://discuss.atom.io/t/is-there-an-atom-roadmap/21033
