### ISSUE TITLE
Invisibles enhancements and fixes

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#12157]
In order to clean things up, I'm unifying a number of invisibles-related enhancements and fixes under this one Issue and closing the others.

* [ ] When `showInvisibles` is off, non-visible characters should be non-visible
* [ ] When `showInvisibles` is on, all normally non-visible characters (control characters, zero-width spaces, other Unicode weirdness, etc) should be rendered in some way #1839
* [ ] There should be some way of customizing which non-visible characters are displayed when `showInvisibles` is on (Perhaps by class? i.e. whitespace, control characters, Unicode groups)
* [ ] All displayed invisibles should be visible anywhere on the line when `showInvisibles` is enabled #2572
* [ ] Make it possible for invisibles tab characters to span multiple spaces #3051 (see [implementation suggestion](https://github.com/atom/atom/issues/3051#issuecomment-183003834) by @natbraun)

**Comment by xfq** [comment]
Related: #5490

**Comment by va1m** [comment]
I'm ready to help in testing when the issue will fixed.

**Comment by callumlocke** [comment]
> Related: #6669

Does that mean #6669 will be covered by these changes, or is just related?

**Comment by lee-dohm** [comment]
@callumlocke It means that it is related.

**Comment by callumlocke** [comment]
Ok :) but do you think it would be worth actually adding it to the list? I'm unclear why that particular issue is 'only' related, it seems like it would naturally go in this list, as it involves adding another option regarding invisibles. Then again I don't know the codebase.

**Comment by lee-dohm** [comment]
@callumlocke All of the things I gathered together are refinements to the definition of what an invisible is and how invisibles work. The Issue you're mentioning is more about selections than invisibles themselves, which is why I didn't include it ... but it is related.

**Comment by alexmcmillan** [comment]
#6669 is one of the reasons I gave up on Atom and went back to ST3.  Just sayn'

**Comment by alexrussell** [comment]
@lee-dohm I agree that #6669 is only related in the sense that it related to invisibles in some way, but is otherwise off topic (this is more about ensuring Atom can render everything that should be considered invisible). That said, the "span multiple spaces" task you have there I would put in the same boat in terms of only being related but not the 'core' of this issue.

All that said, I think #6669 is still a pressing concern* because I have a feeling it's something that is very baked into the core. Being related to the under/overlayer (though actually it's been so long since I raised this issue I have no idea how selection is done any more) means that it's not something we can do purely in CSS (without just using colour hacks) or probably even a DOM-manipulating package without a lot of pain and management of state. Like display of control characters and variable-width invisibles, it's something that a core dev just needs to sit down and make decisions about how it needs to be done based on how the rest of the text buffer and editor stuff works and is planned to continue to work far into the future.


\* Arguably the *most pressing* concern on invisibles, as it's turning so many people off Atom - while it doesn't hit as hard as invisibles not showing when they should (e.g. control chars), that doesn't always inform people's motives regarding choosing whether to stick with Atom or not as much as you'd think!

**Comment by awenro** [comment]
> Arguably the most pressing concern on invisibles, as it's turning so many people off Atom - while it doesn't hit as hard as invisibles not showing when they should (e.g. control chars), that doesn't always inform people's motives regarding choosing whether to stick with Atom or not as much as you'd think!

Absolutely. Funny, first I thought, I'll get used to it. Tried the workarounds. But #3051 made me switch back too. Especially if writing Sass.

**Comment by littlebeandog** [comment]
> When showInvisibles is on, all normally non-visible characters (control characters, zero-width spaces, other Unicode weirdness, etc) should be rendered in some way #1839

+1s

**Comment by fractalf** [comment]
Just spend 30min scratching my head before I found a nasty [C2 A0](https://en.wikipedia.org/wiki/Non-breaking_space) in some weird code. Hope this gets fixed :)

**Comment by elmatou** [comment]
#https://github.com/atom/atom/issues/12041

**Comment by octagonal** [comment]
We just experienced a similar issue when trying to figure out why our code wasn't compiling. As you can imagine it was quite difficult to find the problematic '[zero width character](http://www.fileformat.info/info/unicode/char/200B/index.htm)' in question 😉 .

As a temporary solution we went into vim with `:set list` turned on. Doing this shows will show such characters as `<200b>` which is the behaviour I expected Atom to have as well.

I'd be glad to help with testing when the issue gets resolved.

**Comment by lifzgreat** [comment]
> Funny, first I thought, I'll get used to it. Tried the workarounds. But #3051 made me switch back too. 

I switched back too :( I ended up leaving Atom and going back to Sublime Text 3 because this issue. It's crazy how important this becomes when it's missing! I'm subscribed to this issue if/when it gets fixed!

**Comment by iredwards** [comment]
Invisible invisibles is the deal-breaker for me. My sources have mixed space types so I keep having to open another editor to do work. I hoped Atom would be a good cross platform editor, but because of invisible spaces, it is not usable.

**Comment by Arcanemagus** [comment]
@iredwards Atom can show (some) invisibles like spaces, this issue is about enhancements to that existing functionality.

**Comment by iredwards** [comment]
@Arcanemagus I guess I'm not sure what issue # is appropriate for this.  I haven't been able to figure out how to show spaces that aren't leading or trailing. I tried to install the atom-innerspaces package. What I really need is a way to distinguish between vanilla spaces and utf8 nonbreaking spaces, like 0xc2 0xa0, and mixtures of tabs and various spaces within a line.

**Comment by Arcanemagus** [comment]
@iredwards Ah, your "doesn't show spaces" was a bit misleading then 😛. This is exactly the issue you are looking for then, as what you are talking about is a combination of points 2 (https://github.com/atom/atom/issues/1839) and 4 (https://github.com/atom/atom/issues/2572).

**Comment by calumk** [comment]
+1 for this issue.
Causing me all sorts of problems "cleaning" table data coppied from excel/word

**Comment by polarathene** [comment]
Just ran into #2572 myself. `atom-innerspace` was apparently a solution in the past but Atom devs broke it with an update and have been reluctant to make it possible for the package to work again according to [this closed issue](https://github.com/squizlabs/atom-innerspace/issues/6). 

Would be great to see this natively supported by Atom.

**Comment by 6** [comment]
This package solved the issue for me https://atom.io/packages/show-invisibles-plus, although as others have said a native solution would be great as well.

**Comment by kukac7** [comment]
screenshots:

sublime
<img width="505" alt="screen shot 2017-02-16 at 10 05 22" src="https://cloud.githubusercontent.com/assets/1240104/23014673/2e98f360-f430-11e6-8c77-be437c927e1b.png">

atom
<img width="580" alt="screen shot 2017-02-16 at 10 06 01" src="https://cloud.githubusercontent.com/assets/1240104/23014681/35f93188-f430-11e6-808c-67cb1af9bc87.png">

windows chrome
<img width="230" alt="screen shot 2017-02-16 at 10 08 54" src="https://cloud.githubusercontent.com/assets/1240104/23014689/4412392c-f430-11e6-94dc-536c24410d6d.png">

😭

**Comment by kamaradski** [comment]
This is the only deal breaker as to why my buddies and I are not using this tool anymore.

I run into these frequently, and since these are invisible it's always too late. (read: extra work to fix/remove/replace these)

In other editors (even CLI) I immediately see these and can correct them in 1 go without the need to switch tools to do a post-check.

**Comment by rayfoss** [comment]
https://atom.io/packages/show-invisibles-plus seemed like a miracle drug... but it doesn't actually work all that well. It misses lots of characters and its settings don't play well with the built in invisibles functionality.

**Comment by fractalf** [comment]
@atom_developers: is this very hard to fix, is that why it's not been done?

There are basically 2 "failings" as I see it:

1) Show invisibles (those working as of now) on the **whole** line, not just before the first character (this would at least show spaces that are not really spaces)

2) Show weird characters as a symbol of sorts (mentioned many times in this thread)

I have a hard time seeing these issues being so hard to fix, but then again, I have now idea how things are done developing atom..

ps. the "show-invisibles-plus" package isn't working for me

**Comment by juni0r** [comment]
I'll  just __+1__ this and leave...

**Comment by olleicua** [comment]
+1

**Comment by olleicua** [comment]
Is there a reason we could, for example, wrap every whitespace character in a span and give those spans a :before pseudo-selector with the desired display character in it absolute positioned into place? Or, even perhaps give whitespace spans a special font for this purpose? This doesn't seem like it should be difficult..

**Comment by alexrussell** [comment]
@olleicua which exact issue is your suggestion here solving? The current "show invisibles" will should you all whitespace characters if that's what you want. This issue is here to group a bunch of slightly-more-edge-case issues, such as showing non-printable characters (like NUL, BEL, etc.). And my issue (#6669) is about showing invisibles only for the current selection, which it looks like your suggestion is most suited for.

**Comment by olleicua** [comment]
Oh, nevermind, for some reason it wasn't working for me but now it is..

**Comment by olleicua** [comment]
@alexrussell actually it is only showing me leading whitespace. I want to show all whitespace..

**Comment by alexrussell** [comment]
Ahh yes good point. I forgot that Atom only shows you whitespace at the beginning of the line.

**Comment by olleicua** [comment]
so.. what exactly is preventing this basic feature?

**Comment by 50Wliu** [comment]
@olleicua Nothing is except that no PRs have been opened yet.  Anyone who would like to see these enhancements implemented is welcome to investigate and open a PR.

**Comment by rayfoss** [comment]
The problem isn't as bad as it used to be, I used to have issues with Carriage Return U+21B5, which used to hide between characters and eat the cursor for one stroke. Now that actually shows as a proper symbol. Even the previously mentioned U+00A0 NO-BREAK SPACE isn't all that bad, as it shows as a normal space, which is problematic, but not as bad as it used to be.

Below is a carriage return, followed by nbsp, followed by a space, followed by hello
![screen shot 2018-02-12 at 11 56 20 am](https://user-images.githubusercontent.com/876076/36111637-6d5072e4-0fec-11e8-8839-9a3ab7f62270.png)

seems like the fix for carriage return could be applied to the rest of the nasties...

**Comment by oisnot** [comment]
Found this zero width space in git. Not visible in Atom even with Show invisible enabled. This bug caused lots of problems debugging why a docker service wouldn't start. 

Atom 1.34.0

![skjermdump fra 2019-02-15 11-29-51](https://user-images.githubusercontent.com/2698541/52850945-1fda8680-3115-11e9-87cd-fe50f3f462f0.png)

**Comment by rediris** [comment]
Atom `1.34.0`:
With `Show Invisibles` enabled, the following zero width character space remains invisible:

<img width="150" alt="screen shot 2019-03-04 at 10 52 23 am" src="https://user-images.githubusercontent.com/1010395/53744799-ba53fd00-3e6b-11e9-9c35-6c8b0527c060.png">

**Comment by wesinator** [comment]
Also null (0x00 , `\0`) characters are not displayed visibly, even with `Show Invisibles`

They should display a bullet or something regardless of the Show Invisibles setting, to let the user know there are extra chars
![image](https://user-images.githubusercontent.com/5124946/55851892-a9607080-5b28-11e9-9e23-1e83a76567bd.png)

This can really mess things up if text has null chars

#18734

**Comment by wesinator** [comment]
I'd like to point out, VS Code does the sane thing and shows null characters visibly as an unprintable char
![image](https://user-images.githubusercontent.com/5124946/57406979-1874c780-71b0-11e9-816e-992aa8c98a59.png)

**Comment by PgLoLo** [comment]
Any progress on showing invisible inner spaces?

**Comment by ccube** [comment]
If the problem is finding non-printing characters in your code, use this regex search:
[^[:print:][:space:]]
