### ISSUE TITLE
Reported potential regressions in v1.13-beta

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#13199]
This is a tracking issue for things that the maintainers have vetted as potential regressions in v1.13-beta.

* [x] https://github.com/atom/atom/issues/13182
* [x] https://github.com/atom/atom/issues/13189
* [x] https://github.com/atom/atom/issues/13206
* [x] https://github.com/atom/find-and-replace/issues/809
