### ISSUE TITLE
Reported potential regressions in v1.12 release

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#13198]
This is a tracking issue for things that the maintainers have vetted as potential regressions in v1.12.

* [x] https://github.com/atom/atom/issues/13182 - only reported in Beta, moved to #13199
* [x] Slow startup from the dock https://github.com/atom/atom/issues/9406
* [x] Shelling out to collect environment variables is creating runaway 100% CPU processes on Linux https://github.com/atom/atom/issues/13084
* [x] In some scenarios, opening Atom on Linux results in 100% CPU usage of a core https://github.com/atom/atom/issues/13317
* [x] Uncaught exception in keymap https://github.com/atom/atom/issues/13181
* [x] atom --profile-startup doesn't work on 1.12.0  https://github.com/atom/atom/issues/13171
* [x] AltGr-e resolves to e on Swedish keymap - should be €  https://github.com/atom/atom-keymap/issues/174
* [x] Cannot input multibyte char via Japanese IME when pending state settled https://github.com/atom/atom-keymap/issues/172
* [x] RPM Install: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory https://github.com/atom/atom/issues/13176
* [x] Uncaught exception in keymap for certain languages https://github.com/atom/atom/issues/13296
* [ ] [Discuss: mysterious slowdowns](https://discuss.atom.io/t/anyone-else-experiencing-slowdowns-on-windows-release-1-12-0/35743)
* [x] https://discuss.atom.io/t/atom-1-12-0-is-getting-stuck-in-macos-sierra/35753 - Appears to be caused by community package

**Comment by anatoli26** [comment]
@lee-dohm, could you please investigate if it's a regression or what, the last comment in #9643 and #10517, I'm seeing this extremely annoying behavior since 1.12.1 update in linux.

**Comment by lee-dohm** [comment]
@anatoli26 In order to determine if this is a regression, we'll need you to file a new Issue with as much information as you can, including steps to reproduce the problem.

**Comment by anatoli26** [comment]
FYI, just found the cause of this particular problem: #13326.

**Comment by as-cii** [comment]
I think we should discuss about hotfixing https://github.com/electron/electron/issues/8116 (when it ships), https://github.com/atom/atom/pull/13386 and https://github.com/atom/atom/pull/13372 into stable and beta. @atom/maintainers: thoughts? 💭

**Comment by Ben3eeE** [comment]
Open concerns if we decide to hotfix (which I think we should do):

* More problems with the keymap as we are currently pretty stable with it. I would want some time to test out https://github.com/electron/electron/issues/8116 to ensure that it works properly before we ship. We have had many issues and I know all of them by now to be able to test for problems.
* Should we hotfix dead keys on Windows? @as-cii what is the status on that?
* There was a similar problem for `libXScrnSaver` on Ubuntu 14.04 [reported here](https://discuss.atom.io/t/latest-12-6-1-does-not-open-on-ubuntu-14-04/36526). Maybe we should ensure everything works properly on Ubuntu 14.04 before shipping the hotfix?

**Comment by as-cii** [comment]
> More problems with the keymap as we are currently pretty stable with it. I would want some time to test out electron/electron#8116 to ensure that it works properly before we ship. We have had many issues and I know all of them by now to be able to test for problems.

That would be awesome, @Ben3eeE. Thanks! 💯 

> Should we hotfix dead keys on Windows? @as-cii what is the status on that?

I am a little torn on whether we should address it, as we had only one report and on a non-standard keyboard layout. Fixing it with an elegant solution is non-trivial and it's unclear it's worth the effort. For now, I think the next hotfix can go out without that specific fix.

> There was a similar problem for libXScrnSaver on Ubuntu 14.04 reported here. Maybe we should ensure everything works properly on Ubuntu 14.04 before shipping the hotfix?

I am testing it right now on Ubuntu 14.04: I will open a pull request if I can reproduce. I agree it should ship with the next stable and beta hotfix releases.

**Comment by kevinsawicki** [comment]
> I think we should discuss about hotfixing electron/electron#8116 (when it ships)

It has shipped in Electron 1.3.13, I've updated #13353 accordingly.

**Comment by as-cii** [comment]
There was another report of a missing dependency on CentOS (https://github.com/atom/atom/issues/13417). It has been fixed in #13421 and, since it affects both beta and stable, it should go out with the next hotfix.

**Comment by lee-dohm** [comment]
@iolsen @nathansobo It appears that Atom v1.12.7 contains Electron v1.3.13 which should address the "mysterious slowdowns" item above? If so, can we check that off and close this Issue now?

**Comment by nathansobo** [comment]
@leedohm if you think it does I'm on board. Can you link me to the evidence that's making you think the Electron upgrade helped? I'm curious.

**Comment by lee-dohm** [comment]
@nathansobo Actually, I don't have any evidence other than my trust in your knowledge and judgement and [this post of yours](https://discuss.atom.io/t/anyone-else-experiencing-slowdowns-on-windows-release-1-12-0/35743/10?u=leedohm). It was my assumption that because you said it was an Electron issue and there was a bump in Electron that it would be to address it. My mistake if that wasn't correct :grinning:

**Comment by iolsen** [comment]
I'm not aware of any deliberate performance fixes in that Electron upgrade, FWIW.

**Comment by nathansobo** [comment]
Yeah, that's just a hotfix for keyboard stuff. I doubt it would help solve the mystery. I have seen the weirdo dev tools slowness persist and have hope that an Electron upgrade could help that piece of things.

**Comment by 50Wliu** [comment]
Can we comment on that thread and ask if anyone is still experiencing slowdowns on the latest version?  Since the last comment was almost a month ago.

**Comment by lee-dohm** [comment]
Good idea. Done.
