### ISSUE TITLE
Reported potential regressions in v1.13 release

### ISSUE THREAD

**Issue by Ben3eeE** [atom/atom#13628]
This is a tracking issue for things that the maintainers have vetted as potential regressions in v1.13.

## Open
* [ ] https://github.com/atom/atom/issues/13542 Select to beginning or end of word in macOS Sierra save dialog not working
* [x] https://github.com/atom/tree-view/issues/1023: Tree-View Closed When Opening Folder
* [ ] https://github.com/atom/atom/issues/13736 Assigning editor's height explicitly via position: 'absolute' deprecation. Duplicate of https://github.com/atom/atom/issues/13653 but with repro steps.
* [ ] https://github.com/atom/atom/issues/13767 Unable to capture a CPU profile

## Fixed
* [x] https://github.com/atom/markdown-preview/issues/464 Uncaught TypeError: _this.scrollDown is not a function
* [x] https://github.com/atom/markdown-preview/issues/421 Fenced code blocks are being rendered with a taller-than-necessary box
* [x] https://github.com/atom/atom/pull/13573 Install only the 64 bit version of libXss.so.1.
* [x] https://github.com/atom/markdown-preview/issues/462 - Uncaught TypeError: _this.css is not a function
* [x] https://github.com/atom/atom/issues/13625 - Can't zoom using Ctrl+MWheel
* [x] https://github.com/atom/markdown-preview/issues/461 - html generated from markdown-preview doesn't have syntax color for code block.
* [x] https://github.com/atom/atom/issues/13663 - CssSyntaxErrors for the Font Family setting that prevent startup
* [x] https://github.com/atom/metrics/issues/76 - fixed by pr https://github.com/atom/metrics/pull/80
* [x] https://github.com/atom/bracket-matcher/issues/271 - bracket-matcher throws error when Sublime-Style-Column-Selection is installed and used.

**Comment by as-cii** [comment]
@atom/maintainers: as mentioned during our last standup (and now that all the reported regressions have been fixed), I think it might be a good time to ship an hotfix to stable and beta. What do you think? 💭

@ungb: I have already cherry-picked the relevant commits onto [1.13-releases](https://github.com/atom/atom/tree/1.13-releases) and [1.14-releases](https://github.com/atom/atom/tree/1.14-releases) and will create the draft releases soon so that you could give them a try before putting the releases out tomorrow morning (Pacific).

**Comment by ungb** [comment]
thanks @as-cii, I've already tested all but the bracket-matcher issue on master, saw that everything was working as expected.  I'll take a look again once the draft is completed.

**Comment by 50Wliu** [comment]
#13542 is not a regression in 1.13.  The version the reporter is using is 1.12.8.

**Comment by lee-dohm** [comment]
@50Wliu Yes, but I confirmed that it still reproduces in v1.13. So it is a regression that exists in v1.13 :grinning:

**Comment by Ben3eeE** [comment]
@lee-dohm Should https://github.com/atom/markdown-preview/issues/421 also be added since it is a regression that exists in v1.13?

**Comment by lee-dohm** [comment]
@Ben3eeE Yes, added.

**Comment by lee-dohm** [comment]
Added https://github.com/atom/atom/issues/13767 to the list.
