### ISSUE TITLE
Reported potential regressions in v1.14-beta

### ISSUE THREAD

**Issue by Ben3eeE** [atom/atom#13640]
This is a tracking issue for things that the maintainers have vetted as potential regressions in v1.14-beta.

## Open

* [x] https://github.com/atom/markdown-preview/issues/462 - Uncaught TypeError: _this.css is not a function
* [x] https://github.com/atom/atom/pull/13573 Install only the 64 bit version of libXss.so.1.
* [x] https://github.com/atom/atom/issues/13647 Window title is `untitled` when no files are open
* [x] https://github.com/atom/atom/issues/13738 Atom Beta 1.14 TextEditor.getPath() has inconsistent behavior with symlinks
## Fixed in 1.14.0-beta3

* [x] https://github.com/atom/atom/issues/4619#issuecomment-273122379 - Uncaught TypeError: Cannot read property slice of undefined (Can only reproduce with 1.14 or later using the steps in that comment)
* [x] https://github.com/atom/find-and-replace/issues/841 - Uncaught TypeError: Cannot read property 'slice' of undefined (find-and-replace package).  Fixed with https://github.com/atom/find-and-replace/pull/844

**Comment by maxbrunsfeld** [comment]
#13738 Is still an issue, but it's not something we can fix before the 1.14 release. In fact, there's a bug in macOS that may preclude us from fixing it for a long time. See https://github.com/atom/atom/issues/13738#issuecomment-277802322.

**Comment by Ben3eeE** [comment]
Everything here is fixed.
