### ISSUE TITLE
Reported potential regressions in v1.14 release

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#13778]
This is a tracking issue for things that the maintainers have vetted as potential regressions in v1.14.

## Fixed in 1.14.1
* [x] https://github.com/atom/find-and-replace/issues/854 Select Next doesn't work on multiline selections

**Comment by ungb** [comment]
Bugsnag issues found:

- [ ] https://app.bugsnag.com/atom/atom/errors/589bdf9418bc577b31535548?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open&filters%5Bversion.introduced_in%5D%5B%5D%5Bvalue%5D=1.14.0&filters%5Bversion.introduced_in%5D%5B%5D%5Btype%5D=eq
Stack Trace:
```
TypeError·Cannot read property 'buildTextEditor' of null
Full TraceRaw
/app.asar/src/text-editor-element.js:186TextEditorElement.buildModel	
 /app.asar/src/text-editor-element.js:182TextEditorElement.getModel
```

- [ ] https://app.bugsnag.com/atom/atom/errors/589c233518bc577b3153570a?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open&filters%5Bversion.introduced_in%5D%5B%5D%5Bvalue%5D=1.14.0&filters%5Bversion.introduced_in%5D%5B%5D%5Btype%5D=eq
Stack Trace:
```
Error·Pane has been destroyed
Raw
/app.asar/src/pane.js:847module.exports.Pane.activate	
 /app.asar/src/workspace-element.js:141module.exports.WorkspaceElement.handleFocus
```

- [ ] https://app.bugsnag.com/atom/atom/errors/589c703518bc577b31535ae4?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open&filters%5Bversion.introduced_in%5D%5B%5D%5Bvalue%5D=1.14.0&filters%5Bversion.introduced_in%5D%5B%5D%5Btype%5D=eq
Stack trace:
```

/app.asar/src/text-editor-presenter.js:577module.exports.TextEditorPresenter.updateOverlaysState	
 /app.asar/src/text-editor-presenter.js:155module.exports.TextEditorPresenter.getPostMeasurementState	
 /app.asar/src/text-editor-component.js:202module.exports.TextEditorComponent.updateSync	
 /app.asar/src/text-editor-component.js:323none	
 /app.asar/src/view-registry.js:219module.exports.ViewRegistry.performDocumentUpdate	
 /app.asar/src/view-registry.js:3none
```

- [ ]  https://app.bugsnag.com/atom/atom/errors/589c2f2318bc577b31535792?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open&filters%5Bversion.introduced_in%5D%5B%5D%5Bvalue%5D=1.14.0&filters%5Bversion.introduced_in%5D%5B%5D%5Btype%5D=eq

Stack Trace:
```
TypeError·Cannot read property '-1' of undefined
Full TraceRaw
/app.asar/src/decoration-manager.js:151module.exports.DecorationManager.decorationsStateForScreenRowRange	
 /app.asar/src/text-editor.js:1698module.exports.TextEditor.decorationsStateForScreenRowRange	
 /app.asar/src/text-editor-presenter.js:1381module.exports.TextEditorPresenter.fetchDecorations	
 /app.asar/src/text-editor-presenter.js:125module.exports.TextEditorPresenter.getPreMeasurementState	
 /app.asar/src/text-editor-component.js:264module.exports.TextEditorComponent.updateSyncPreMeasurement	
 /app.asar/src/text-editor-component.js:196module.exports.TextEditorComponent.updateSync	
 /app.asar/src/text-editor-component.js:323none	
 /app.asar/src/view-registry.js:219module.exports.ViewRegistry.performDocumentUpdate	
 /app.asar/src/view-registry.js:3none
```


- [ ] https://app.bugsnag.com/atom/atom/errors/589c171018bc577b3153569d?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open&filters%5Bversion.introduced_in%5D%5B%5D%5Bvalue%5D=1.14.0&filters%5Bversion.introduced_in%5D%5B%5D%5Btype%5D=eq
Stack Trace:

```
https://app.bugsnag.com/atom/atom/errors/589befd418bc577b31535590?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open&filters%5Bversion.introduced_in%5D%5B%5D%5Bvalue%5D=1.14.0&filters%5Bversion.introduced_in%5D%5B%5D%5Btype%5D=eq

```

```
TypeError·Cannot read property 'length' of undefined
Raw
/app.asar/node_modules/find-and-replace/lib/find-view.js:662module.exports.FindView.firstMarkerIndexAfterCursor	
/app.asar/node_modules/find-and-replace/lib/find-view.js:615module.exports.FindView.selectFirstMarkerAfterCursor	
/app.asar/node_modules/find-and-replace/lib/find-view.js:3selectFirstMarkerAfterCursor	
/app.asar/node_modules/find-and-replace/lib/find-view.js:861module.exports.FindView.toggleRegexOption	
/app.asar/node_modules/find-and-replace/lib/find-view.js:3none	
/app.asar/node_modules/jquery/dist/jquery.js:4435dispatch	
/app.asar/node_modules/jquery/dist/jquery.js:4121elemData.handle
```

- [ ] https://app.bugsnag.com/atom/atom/errors/589befd418bc577b31535590?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open&filters%5Bversion.introduced_in%5D%5B%5D%5Bvalue%5D=1.14.0&filters%5Bversion.introduced_in%5D%5B%5D%5Btype%5D=eq
