### ISSUE TITLE
Iteration Plan: June 11 - June 22, 2018

### ISSUE THREAD

**Issue by daviwil** [atom/atom#17501]
This is the two week development plan for Atom for **June 11 - June 22, 2018.**

### :atom: Atom Core

- [x] Prepare documentation re: Atom 1.28 color rendering (e.g., release blog post, release notes, flight manual) (@jasonrudolph)
- [x] Propose remedy for https://github.com/atom/atom/issues/17409. If we think a code change is appropriate, then make that change. (@jasonrudolph)
- [x] Decaffeinate atom/metrics (@jasonrudolph)
- [x] [Decide](https://github.com/atom/telemetry/issues/8#issuecomment-397654650) whether we'll send metrics to telemetry in real-time or in batches (@jasonrudolph)
- [x] :ship: Ship 1.28.0 and 1.29.0-beta0 (@daviwil)
- [x] :memo: Write and publish release blog post (@daviwil)
- [ ] :memo: Publish RFC for moving "small" bundled packages back into atom/atom (@daviwil)
- [ ] :memo: Prototype format for "This Month in Atom" blog series (@daviwil)
- [ ] :keyboard: Implement "Atom Nightly Releases" RFC for private testing (@daviwil)
- [x] :mag: Review [atom/language-gfm#149](https://github.com/atom/language-gfm/pull/149) (@daviwil)
- [ ] :mag: Review [atom/atom-select-list#27](https://github.com/atom/atom-select-list/pull/27) (@daviwil)

### :deciduous_tree: [Tree-sitter](https://github.com/orgs/atom/projects/12)

- [x] :ship: HTML Parser (@queerviolet's first :ship:)
- [ ] Nested languages support [#17932](https://github.com/atom/atom/issues/17392) (@maxbrunsfeld + @queerviolet)

**Comment by daviwil** [comment]
Next Iteration Plan issue: https://github.com/atom/atom/issues/17579
