### ISSUE TITLE
Iteration Plan: July 9 - July 20, 2018

### ISSUE THREAD

**Issue by daviwil** [atom/atom#17660]
This is the two week development plan for Atom for **July 9 - July 20, 2018.**

### :atom: Atom Core

- [x] Add metric to help assess awareness/approachability of look-and-feel customizability (https://github.com/atom/metrics/pull/96) @jasonrudolph
- [x] Add metric to help assess awareness/approachability of init script customizability (https://github.com/atom/metrics/pull/95) @jasonrudolph
- [x] Add metric to help assess Atom's reach across various developer ecosystems (https://github.com/atom/metrics/pull/98) @jasonrudolph
- [x] Ship Atom 1.28.2 and 1.29.0-beta2 with resolution for https://github.com/atom/atom/issues/17557 @jasonrudolph
- [x] Merge Atom Nightly Releases PR #17538 (@daviwil)
- [ ] Draft announcement post for Atom Nightly channel (@daviwil)
- [ ] Finish copy for new Atom Nightly channel landing page (@daviwil)
- [x] Draft RFC for moving "small" bundled packages back into atom/atom (https://github.com/atom/atom/pull/17674) (@daviwil)
- [ ] ~Draft RFC for shipping Atom releases more frequently (@daviwil)~
- [ ] Automate Atom Stable/Beta draft release creation with VSTS (@daviwil)

### :deciduous_tree: Tree-sitter

- [x] Merge PR #17551 (@maxbrunsfeld, @queerviolet)
- [x] Finish https://github.com/atom/language-ruby/pull/225
- [ ] Switch on tree-sitter by default
  - [ ] Decide on / implement config setting to disable it
  - [ ] Test with top-N community themes
- [ ] Explore tree-sitter search/editing repl

**Comment by robertrossmann** [comment]
As an external observer, it would be super-helpful to link the relevant issue/PR here when an item is marked as completed/in progress so I can go and look at it as it progresses (if it's public). Now I see that _Draft RFC for moving "small" bundled packages back into atom/atom_ is checked as completed but I have to go and look around to find the details for that RFC.

Thanks! ❤️

**Comment by Arcanemagus** [comment]
Added links for the completed items @robertrossmann 😉.
