### ISSUE TITLE
Iteration Plan: July 23 - August 3, 2018

### ISSUE THREAD

**Issue by asheren** [atom/atom#17739]
This is the two week development plan for Atom for **July 23 - August 3, 2018.**

### :atom: Atom Core

- [ ] Draft announcement post for Atom Nightly channel
- [ ] Finish copy for new Atom Nightly channel landing page 
- [x] Prototype Atom Stable/Beta draft release creation with VSTS
- [x] [Overly generic css selector on menu](https://github.com/atom/find-and-replace/issues/1032)
- [x] [PaneItem onDidTerminatePendingState is ignored unless onDidDestroy is defined](https://github.com/atom/atom/issues/17535)
- [ ] Check in on [Atom doesn't use gtk3 file dialog on Gnome 3](https://github.com/atom/atom/issues/8729)
- [x] Roll the Rail Cars
- [ ] Publish stable/beta draft Linux packages to packagecloud
- [x] [high lag on long lines](https://github.com/atom/autocomplete-plus/issues/949)
- [x] ~~[start Migration to CircleCI 2.0](https://github.com/atom/atom/pull/17105)~~ Migrate to VSTS for macOS builds (https://github.com/atom/atom/pull/17749, https://github.com/atom/atom/pull/17770)
- [ ] [watching open files for changes is broken after `git pull`](https://github.com/atom/atom/issues/17355)
- [ ] [SASS/SCSS Autocomplete does not work](https://github.com/atom/autocomplete-plus/issues/975)

### :deciduous_tree: Tree-sitter

- [ ] [Add system for customizing tree-sitter syntax highlighting by matching regexes ](https://github.com/atom/atom/pull/17738)
- [ ] [Highlight certain built-in functions and variables in JavaScript](https://github.com/atom/language-javascript/pull/587) 
- [ ] Highlight certain built-in functions and variables in Python
 - [ ] [Highlight certain built-in functions and variables in Ruby](https://github.com/atom/language-ruby/pull/235)
- [X] [Highlight escape sequences in string literals in Python](https://github.com/tree-sitter/tree-sitter-python/pull/33)
- [X] [Highlight escape sequences in string literals in Ruby](https://github.com/tree-sitter/tree-sitter-ruby/pull/88)
- [ ] [Highlight escape sequences in string literals and regexes in JavaScript](https://github.com/tree-sitter/tree-sitter-javascript/issues/79)
- [x] [Fix python syntax highlighting regression](https://github.com/atom/atom/pull/17740)

### 📞 ⌨️  Teletype
- [x] Update dependencies to address `npm audit` findings [#51](https://github.com/atom/teletype-server/pull/51)

**Comment by asheren** [comment]
Previous Iteration plan: https://github.com/atom/atom/issues/17660

**Comment by asheren** [comment]
Next iteration plan: https://github.com/atom/atom/issues/17808
