### ISSUE TITLE
Iteration Plan: August 6 - August 17

### ISSUE THREAD

**Issue by asheren** [atom/atom#17808]
This is the two week development plan for Atom for **July 23 - August 3, 2018.**

### :atom: Atom Core

- [ ] Finish copy for new Atom Nightly channel landing page 
- [ ] Prototype Atom Stable/Beta draft release creation with VSTS
- [ ] Check in on [Option to disable discrete GPU](https://github.com/atom/atom/issues/17694)
- [ ] Publish stable/beta draft Linux packages to packagecloud
- [ ] [macOS Mojave Beta: Atom requests access to Contacts and Calendars](https://github.com/atom/atom/issues/17687)
- [ ] [Many (all?) core packages show "No README"](https://github.com/atom/settings-view/issues/1069)
- [ ] Add tickets in to backlog for communications and process framework related to Q3 goals (Coming soon)
- [ ] [Uncaught TypeError: Character index must be a number](https://github.com/atom/toggle-quotes/issues/59)
- [ ] [Command palette closes if you click on the palette's scrollbar](https://github.com/atom/atom/issues/17236)

### :deciduous_tree: Tree-sitter

- [ ] Test treet-sitter syntax highlighting with the top 10 community themes
 - [ ] [Uncaught TypeError: grammar.tokenizeLines is not a function](https://github.com/atom/atom/issues/16581)
- [ ] [Highlight escape sequences in string literals in Go](https://github.com/tree-sitter/tree-sitter-go/pull/26)
- [ ] [Add escape sequences in string literals and regexes in JavaScript grammar](https://github.com/tree-sitter/tree-sitter-javascript/issues/79)
- [ ] [Maximum call size exceeded](https://github.com/atom/atom/issues/16583)
- [ ] [Ruby files are recognized as C++ when tree-sitter grammars are enabled](https://github.com/atom/atom/issues/17682)
- [ ] [Atom out of memory crash when copying lines](https://github.com/atom/atom/issues/16582)

[Previous Sprint](https://github.com/atom/atom/issues/17739)
