### ISSUE TITLE
Turn on tree-sitter by default

### ISSUE THREAD

**Issue by queerviolet** [atom/atom#17810]
## Summary

[Tree-sitter](https://github.com/tree-sitter/tree-sitter) has been in testing for a while now. We're switching it on! This might affect how the syntax highlighting of some files looks, but nothing should look broken.

## Motivation

Tree-sitter is a new incremental parsing system for Atom. It maintains a living parse tree, enabling all kinds of interesting extensions: search-for-similar-expression, refactoring assistance, and so on. None of that's implemented yet. For now, it's just making syntax highlighting blazing fast, and gives us the ability to embed languages within each other, perfectly highlighting Javascript inside `<script>` tags, HTML template strings in Javascript, `<script>` tags inside HTML template strings inside Javascript inside ERB, and on and on, until you throw away this whole artisanal templating system you've evidently grown and switch to React. Which we also parse.

## Describe alternatives you've considered

We did consider not doing this, but decided instead to do it.

## TODO

- [x] [Test tree-stter with popular themes](https://github.com/atom/atom/issues/17811) #17811
- [x] Update the flight manual (https://github.com/atom/flight-manual.atom.io/pull/478)
- [ ] [Flip the switch](https://github.com/atom/flight-manual.atom.io/pull/17879)

**Comment by danPadric** [comment]
Good day,

I am of the opinion that the designers of this fine software does not use Atom. 

Please; before making `Tree-Sitter` a default, look into making the standard snippets available again. The original grammar and `Tree-Sitter` based grammar do not share the scope name.

Other service providers (community packages) based on grammar scope names are also get broken. My humble suggestion is to at least have the grammar change mentioned in the `flight-manual`. Else have the `depreciation-cop` pick the fact up if a non-`tree-sitter` grammar is referenced.

Please consider making these prelude preparations before switching `Tree-Sitter` functionality on by default. Thanks in advance for your attention to this matter.

Regards from a <small>mostly</small> happy Atom user.

**Comment by Ben3eeE** [comment]
@danPadric Snippets have been available when using tree-sitter since Atom 1.25. See https://github.com/atom/atom/issues/16621.

**Comment by Ben3eeE** [comment]
@danPadric For keybindings I opened https://github.com/atom/atom/issues/17820. Is there any other issues you were considering? Please open a new issue for these!

**Comment by lee-dohm** [comment]
> I am of the opinion that the designers of this fine software does not use Atom.

@danPadric your comment above is a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. You may consider this an official warning.

**Comment by maxbrunsfeld** [comment]
@danPadric Which snippets aren't working for you? I know snippets didn't work when we first shipped Tree-sitter mode, but I thought that was fixed by https://github.com/atom/snippets/pull/264. Can you open an issue with detailed information about the problem you're seeing?

**Comment by maxbrunsfeld** [comment]
> My humble suggestion is to at least have the grammar change mentioned in the flight-manual.

We do plan to do that.

**Comment by Aerijo** [comment]
Community Tree-sitter grammars seem to have a hard time installing; I tried on a new Ubuntu VM, and it couldn't install `language-latex2e` because of a missing `make` command.

I doubt Atom can package it's own build tools, but maybe it can catch this error and ask the user if they want to install it? It seems `make` is the only requirement.

This is particularly important as more grammars are made for Tree-sitter; many people will not have `make` installed, especially non-developers.

**Comment by danPadric** [comment]
Dear Atom Contributors,

@lee-dohm: 
You are right. My behaving was that of a child: emotionally charged, unsubstantiated and unprofessional. I have done wrong and regret my approach. I apologize to you and your fellow team members.

@queerviolet:  
I am sorry for starting my conversation in this disrespectful way and on your topic. I am sorry.

@Ben3eeE:
After reading your reply (thank you), I realised the error must be mine mine. I followed up on your note. The short version - I have a localized problem on my machine (me := shame). That that means there is no reason for panic. My notes follows.

To all: I offer no excuses. My behaviour has been wrong. Please forgive me.

**Comment by Ben3eeE** [comment]
@danPadric Can you share the list of community packages you have installed? You can get this by running `apm list --installed`. It seems strange that snippets will stop working with tree-sitter 🙇

**Comment by lee-dohm** [comment]
@danPadric Apology accepted. And thank you for working with us to help make Atom better :grinning:

**Comment by danPadric** [comment]
@lee-dohm:
Thank you.

<br><br>

@Ben3eeE: 
First note I have now 3 versions of Atom on my machine. 1 stable and 2 betas. One Beta has no add on packages. The other Beta has add-on packages that has been added/removed/updated since version 1.16 from a Windows 7 machine.

Please find below descriptions of one stable version and of one Beta version. The Beta version mentioned now is the one that has add-ons. THIS Beta version exhibits the same symptoms as with the stable version. 

_Is there a developer console command I could execute to list the installed and disabled packages for the Beta version? `apm list` does not work, even if running locally._
---

Atom V1.29.0: (1) installed and (2) disabled
```
C:\>apm list --installed
Community Packages (25) C:\Users\wbirm\.atom\packages
├── atom-overtype-mode@0.4.0
├── autocomplete-python@1.10.9 (disabled)
├── flex-tool-bar@2.1.2 (disabled)
├── indent-guide-improved@1.4.13
├── isotope-ui@2.8.5
├── language-lua@0.9.11
├── language-markdown@0.26.0
├── language-powershell@4.0.1
├── language-scl@0.0.1
├── language-stl@0.0.0
├── MagicPython@1.0.12 (disabled)
├── minimap@4.29.8
├── process-palette@0.17.0 (disabled)
├── pure-scroll-sync@0.0.1
├── python-autopep8@0.1.3 (disabled)
├── python-indent@1.1.5 (disabled)
├── sequential-number@0.5.0
├── shell-it@0.5.0
├── simple-align@0.2.0
├── split-diff@1.5.2 (disabled)
├── Sublime-Style-Column-Selection@1.7.4
├── todo-show@2.3.0
├── tool-bar@1.1.7 (disabled)
├── typewriter@0.7.1 (disabled)
└── Zen@0.18.0
```

```
C:\>apm list --disabled
Built-in Atom Packages (7)
├── archive-view@0.65.1
├── background-tips@0.28.0
├── exception-reporting@0.43.1
├── github@0.17.3
├── git-diff@1.3.9
├── welcome@0.36.6
└── language-gfm@0.90.5

Community Packages (9) C:\Users\dp\.atom\packages
├── autocomplete-python@1.10.9
├── flex-tool-bar@2.1.2
├── MagicPython@1.0.12
├── process-palette@0.17.0
├── python-autopep8@0.1.3
├── python-indent@1.1.5
├── split-diff@1.5.2
├── tool-bar@1.1.7
└── typewriter@0.7.1
```

---

Atom V1.30-Beta 1 with add-ons.
```
Directory of D:\AtomBeta\.atom\packages

2018/08/06  11:54    <DIR>          .
2018/08/06  11:54    <DIR>          ..
2017/11/29  11:38    <DIR>          autoclose-html
2018/08/06  11:53    <DIR>          autocomplete-python
2017/11/29  11:38    <DIR>          busy-signal
2018/08/02  20:08    <DIR>          duotone-dark-sea-syntax
2018/08/02  20:04    <DIR>          duotone-dark-space-syntax
2018/07/05  18:03    <DIR>          edit-in-new-tab
2018/06/28  08:24    <DIR>          fonts
2017/11/29  11:38    <DIR>          indent-guide-improved
2018/04/30  14:56    <DIR>          language-babel
2018/06/28  08:26    <DIR>          language-markdown
2018/05/26  18:09    <DIR>          language-scl
2018/05/26  18:09    <DIR>          language-stl
2017/11/29  11:38    <DIR>          MagicPython
2017/09/05  19:25    <DIR>          now-count-words (custom)
2018/04/21  19:01    <DIR>          one-coral-light-syntax
2018/08/06  11:45    <DIR>          one-dark-matte-syntax
2018/08/06  11:54    <DIR>          process-palette
2018/04/16  19:48    <DIR>          python-indent
2018/01/24  09:17    <DIR>          sequential-number
2018/01/29  21:45    <DIR>          typewriter
2018/01/11  16:01    <DIR>          wombat-dark-syntax
2017/11/29  11:38    <DIR>          Zen
```

Thank you for your attention.

**Comment by danPadric** [comment]
@Ben3eeE:
The root cause was found. 

In the list there are two grammar packages that are modified and customized versions that you will not find on public spaces (ie. Github). One of these contain the code lines:

```coffeescript
# D:\AtomBeta\.atom\packages\language-stl\snippets\language-stl.cson
'*':
  'Copyright Notice':
    'prefix': 'legal'
    'body': '// Copyright (c) ${1:2016} ${2:Copyright Holder} ${3:All Rights Reserved.}$4'
```

Amazingly the `'*'` key is no problem for for non-`tree-sitter` grammars. This does however override _all_ snippets for **all** `tree-sitter` grammars!   😮 😊

**Comment by Ben3eeE** [comment]
@danPadric Thank you :bowing_man: I can reproduce this behavior.

@maxbrunsfeld @queerviolet This seems like something we should investigate before turning tree-sitter on by default.

**Comment by maxbrunsfeld** [comment]
@danPadric The issue you identified is fixed on master. Thanks!

**Comment by danPadric** [comment]
@Ben3eeE ,  @maxbrunsfeld: 
Thank you for your dedication to the topic.

I understand that the `*` key in the global user `snippets.cson` identify snippets that are applied to all grammar scopes. May I assume that this concept will be available for `Tree-Sitter` and `Textmate` grammars alike? 

The reason for asking: The newly integrated changes is labelled as `legacy`. Now I am left to wonder if the apply-to-all-grammars (`*` key) would still work for `Tree-Sitter` grammars as intended. 

<br>

_<sub>\* English is not my 1st language: No disrespect intended with the above text.</sub>_

**Comment by maxbrunsfeld** [comment]
> May I assume that this concept will be available for `Tree-Sitter` and `Textmate` grammars alike? 

Yes.

**Comment by UziTech** [comment]
> Other service providers (community packages) based on grammar scope names are also get broken.

I believe this is a real problem that needs to be fixed before automatically changing the default behavior.

A couple examples I know of:

https://github.com/vn-ki/bracket-colorizer/pull/10
https://github.com/AsaAyers/js-hyperclick/issues/95

**Comment by maxbrunsfeld** [comment]
@UziTech This is fixed on master: https://github.com/atom/atom/pull/17881.

**Comment by UziTech** [comment]
@maxbrunsfeld how does that fix the difference in scopes for elements?

### e.g. js regex scopes:

#### without tree-sitter:
- source.js
- string.regexp.js

#### with tree-sitter:
- javascript
- program
- expression_statement
- assignment_expression
- regex
- regex_pattern

Packages that use those scope names are going to need to be updated to work with tree-sitter like [bracket-colorizer](https://github.com/vn-ki/bracket-colorizer/blob/2564114600a70a27cb5615c9041f3b5455ebbcee/lib/bracket-matcher.js#L65-L78)

**Comment by maxbrunsfeld** [comment]
I’m confused; did you rebuild master after the PR I linked to was merged? The scopes aren’t like that any more; that’s why I’m saying the problem is addressed.

There may still be some slight differences, but it’ll just be a matter of tweaking the scope mappings in the various tree-sitter grammar files.
