### ISSUE TITLE
Migrate core package 'base16-tomorrow-dark-theme' into Atom repo

### ISSUE THREAD

**Issue by daviwil** [atom/atom#17836]
This issue tracks the steps necessary to migrate the [`base16-tomorrow-dark-theme`](https://github.com/atom/base16-tomorrow-dark-theme) package into the core `atom/atom` repository under the `packages` path:

## Migration Checklist

**NOTE:** These steps should be taken in a clean branch off of `master` in your local clone of `atom/atom`.  Only one package should be moved in a single pull request.

### Phase 1 - Prepare repo for migration

- [ ] Merge or close existing pull requests on the [`atom/base16-tomorrow-dark-theme`](https://github.com/atom/base16-tomorrow-dark-theme) repository

Some guidelines for merging vs closing PRs:

- **Merge** when the PR is small, useful, has no merge conflicts with `master`, and has passing tests
- **Close** when the changes are non-trivial, the PR has conflicts with `master`, or there are failing tests in CI

If you close a PR, let the user know that we are currently moving the repository over to `atom/atom` so they should feel free to reopen the pull request there once the package code has been migrated.

### Phase 2 - Migrate the package code

- [ ] Clone the  [`atom/base16-tomorrow-dark-theme`](https://github.com/atom/base16-tomorrow-dark-theme) repo into the `packages` path of your local Atom repository and then delete its `.git` subfolder
- [ ] Edit Atom's `package.json` file to change the `base16-tomorrow-dark-theme` entry in `packageDependencies` to reflect the local path of the package:
  ```
  "base16-tomorrow-dark-theme": "file:./packages/base16-tomorrow-dark-theme",
  ```
- [ ] Run a full Atom build using `script/build` and verify that there are no unexpected build errors
- [ ] Launch the Atom binary in the `./out` folder and spot check for any obvious issues
- [ ] Open the Chrome Developer Tools console (<kbd>Ctrl+Shift+I</kbd> or <kbd>Cmd+Option+I</kbd>) and ensure that there are no errors written there.  If there are, add them to this issue and investigate.
- [ ] Commit the migrated package code and any changes to Atom's `package-lock.json` files to your branch using this commit message:
  ```
  :arrow_right: Migrate core package 'base16-tomorrow-dark-theme' into ./packages
  ```
### Phase 3 - Make sure the package works and send a PR

- [ ] Run the full suite of Atom tests with `script/test` and verify that they pass locally
- [ ] If any tests fail, investigate and fix them then commit the fixes to your branch
- [ ] Create a PR against `atom/atom` to verify that CI passes
- [ ] Once CI is clean and the PR is approved, merge it

### Phase 4 - Archive the [`base16-tomorrow-dark-theme`](https://github.com/atom/base16-tomorrow-dark-theme) repo

- [ ] Move all existing issues from the  [`base16-tomorrow-dark-theme`](https://github.com/atom/base16-tomorrow-dark-theme) repo to `atom/atom` using [github-issue-mover](https://github-issue-mover.appspot.com/) or a script
- [ ] Add a label titled `packages/base16-tomorrow-dark-theme` to the migrated issues so that they can be found easily
- [ ] Update the original package repo's README.md to point contributors to the code's new home in `atom/atom`.  You can use the following text:
  <pre>
  ### This package is now a part of the [core Atom repository](https://github.com/atom/atom/tree/master/packages/base16-tomorrow-dark-theme), please direct all issues and pull requests there in the future!
  </pre>
- [ ] Archive the package repository by going to its [Settings page](https://github.com/atom/base16-tomorrow-dark-theme/settings), scroll down to the "Danger Zone" section and click "Archive this Repository"

Migration is now complete! :tada:
