### ISSUE TITLE
Migrate core package 'exception-reporting' into Atom repo

### ISSUE THREAD

**Issue by daviwil** [atom/atom#17842]
This issue tracks the steps necessary to migrate the [`exception-reporting`](https://github.com/atom/exception-reporting) package into the core `atom/atom` repository under the `packages` path:

### Phase 1 - Prepare repo for migration

- [x] Merge or close existing pull requests on the [`atom/exception-reporting`](https://github.com/atom/exception-reporting) repository

Some guidelines for merging vs closing PRs:

- **Merge** when the PR is small, useful, has no merge conflicts with `master`, and has passing tests
- **Close** when the changes are non-trivial, the PR has conflicts with `master`, or there are failing tests in CI

If you close a PR, let the user know that we are currently moving the repository over to `atom/atom` so they should feel free to reopen the pull request there once the package code has been migrated.

### Phase 2 - Migrate the package code

- [x] Create a fresh branch off `master` in your local clone of `atom/atom` with the name `migrate-exception-reporting-package`
- [x] Delete Atom's `node_modules` folder if you've built there before and make sure Atom's `package-lock.json` file is unmodified
- [x] Clone the  [`atom/exception-reporting`](https://github.com/atom/exception-reporting) repo into the `packages` path of your local Atom repository and then delete its `.git` subfolder
- [x] Delete any unnecessary repo configuration files in the `packages/exception-reporting` folder like `appveyor.yml`, `.travis.yml`, `ISSUE_TEMPLATE.md`, and `PULL_REQUEST_TEMPLATE.md`
- [x] Remove any information from the package's `README.md` which will be inaccurate after the migration is complete (e.g. CI status badges or contribution instructions)
- [x] Edit Atom's `package.json` file to change the following:
  - [x] Update the `exception-reporting` entry in `packageDependencies` to reflect the local path of the package:
    ```
    "exception-reporting": "file:./packages/exception-reporting",
    ```
  - [x] Delete the `exception-reporting` entry in the `dependencies` section since it may contain a hardcoded tarball link.  This will help avoid issues in the next step
  - [x] Change the `repository` field to point to the main repo URL `https://github.com/atom/atom`
- [x] Run a full Atom build using `script/build` and verify that there are no unexpected build errors
- [x] Launch the Atom binary in the `./out` folder and manually verify that the migrated package is working without any obvious issues.  For example, if you're migrating a color theme, turn on that theme to make sure that it changes the editor colors as expected.
- [x] Open the Chrome Developer Tools console (<kbd>Ctrl+Shift+I</kbd> or <kbd>Cmd+Option+I</kbd>) and ensure that there are no errors written there.  If there are, add them to this issue and investigate.
- [x] Update the second column of the **exception-reporting** row in `packages/README.md` to reflect the new local path for the package:
  ```
  [`./packages/exception-reporting`](./exception-reporting)
  ```
- [x] Commit the migrated package code and any changes to Atom's `package-lock.json` files to your branch using this commit message:
  ```
  :arrow_right: Migrate core package 'exception-reporting' into ./packages
  ```

### Phase 3 - Make sure the package works and send a PR

- [x] Run the full suite of Atom tests with `script/test` and verify that they pass locally
- [x] If any tests fail, investigate and fix them then commit the fixes to your branch
- [x] Create a PR against `atom/atom` to verify that CI passes
- [x] Once CI is clean and the PR is approved, merge it

### Phase 4 - Archive the [`exception-reporting`](https://github.com/atom/exception-reporting) repo

- [x] Move all existing issues from the  [`exception-reporting`](https://github.com/atom/exception-reporting) repo to `atom/atom` using [github-issue-mover](https://github-issue-mover.appspot.com/) or a script
- [x] Add a label titled `packages/exception-reporting` to the migrated issues so that they can be found easily
- [x] Edit the original package repo's README.md (don't commit directly) to point contributors to the code's new home in `atom/atom`.  You can use the following text:
  ```
  ### This package is now a part of the [core Atom repository](https://github.com/atom/atom/tree/master/packages/exception-reporting), please direct all issues and pull requests there in the future!

  ---
  ```
- [x] Send a PR to the [`exception-reporting`](https://github.com/atom/exception-reporting) repository with the updated README.md so that watchers will be notified of the change.  You do not need to wait for reviews, it can be merged immediately.
- [x] Archive the package repository by going to its [Settings page](https://github.com/atom/exception-reporting/settings), scroll down to the "Danger Zone" section and click "Archive this Repository"

Migration is now complete! :tada:

**Comment by daviwil** [comment]
Migration is complete :tada:

- https://github.com/atom/atom/pull/18140
- https://github.com/atom/exception-reporting/pull/42
