### ISSUE TITLE
Migrate core package 'one-light-ui' into Atom repo

### ISSUE THREAD

**Issue by daviwil** [atom/atom#17856]
This issue tracks the steps necessary to migrate the [`one-light-ui`](https://github.com/atom/one-light-ui) package into the core `atom/atom` repository under the `packages` path:

### Phase 1 - Prepare repo for migration

- [x] Merge or close existing pull requests on the [`atom/one-light-ui`](https://github.com/atom/one-light-ui) repository

Some guidelines for merging vs closing PRs:

- **Merge** when the PR is small, useful, has no merge conflicts with `master`, and has passing tests
- **Close** when the changes are non-trivial, the PR has conflicts with `master`, or there are failing tests in CI

If you close a PR, let the user know that we are currently moving the repository over to `atom/atom` so they should feel free to reopen the pull request there once the package code has been migrated.

### Phase 2 - Migrate the package code

- [x] Create a fresh branch off `master` in your local clone of `atom/atom` with the name `migrate-one-light-ui-package`
- [x] Delete Atom's `node_modules` folder if you've built there before and make sure Atom's `package-lock.json` file is unmodified
- [x] Clone the  [`atom/one-light-ui`](https://github.com/atom/one-light-ui) repo into the `packages` path of your local Atom repository and then delete its `.git` subfolder
- [x] Delete any unnecessary repo configuration files in the `packages/one-light-ui` folder like `appveyor.yml`, `.travis.yml`, `ISSUE_TEMPLATE.md`, and `PULL_REQUEST_TEMPLATE.md`
- [x] Edit Atom's `package.json` file to change the `one-light-ui` entry in `packageDependencies` to reflect the local path of the package:
  ```
  "one-light-ui": "file:./packages/one-light-ui",
  ```
- [x] Delete the `one-light-ui` entry in `package.json`'s `dependencies` section since it may contain a hardcoded tarball link.  This will help avoid issues in the next step
- [x] Run a full Atom build using `script/build` and verify that there are no unexpected build errors
- [x] Launch the Atom binary in the `./out` folder and spot check for any obvious issues
- [x] Open the Chrome Developer Tools console (<kbd>Ctrl+Shift+I</kbd> or <kbd>Cmd+Option+I</kbd>) and ensure that there are no errors written there.  If there are, add them to this issue and investigate.
- [x] Update the second column of the **one-light-ui** row in `packages/README.md` to reflect the new local path for the package:
  ```
  [`./packages/one-light-ui`](./one-light-ui)
  ```
- [x] Commit the migrated package code and any changes to Atom's `package-lock.json` files to your branch using this commit message:
  ```
  :arrow_right: Migrate core package 'one-light-ui' into ./packages
  ```
### Phase 3 - Make sure the package works and send a PR

- [ ] Run the full suite of Atom tests with `script/test` and verify that they pass locally
- [ ] If any tests fail, investigate and fix them then commit the fixes to your branch
- [x] Create a PR against `atom/atom` to verify that CI passes
- [x] Once CI is clean and the PR is approved, merge it

### Phase 4 - Archive the [`one-light-ui`](https://github.com/atom/one-light-ui) repo

- [ ] ~~Move all existing issues from the  [`one-light-ui`](https://github.com/atom/one-light-ui) repo to `atom/atom` using [github-issue-mover](https://github-issue-mover.appspot.com/) or a script~~
- [ ] ~~Add a label titled `packages/one-light-ui` to the migrated issues so that they can be found easily~~
- [x] Update the original package repo's README.md to point contributors to the code's new home in `atom/atom`.  You can use the following text:
  ```
  ### This package is now a part of the [core Atom repository](https://github.com/atom/atom/tree/master/packages/one-light-ui), please direct all issues and pull requests there in the future!

  ---
  ```
- [x] Archive the package repository by going to its [Settings page](https://github.com/atom/one-light-ui/settings), scroll down to the "Danger Zone" section and click "Archive this Repository"

Migration is now complete! :tada:

**Comment by senki** [comment]
Hi,

I am one of the people who maintain a derivative of the [`one-light-ui`](https://github.com/atom/one-light-ui) theme: [`solarized-one-light-ui`](https://github.com/senki/solarized-one-light-ui).

I am watching the [`one-light-ui`](https://github.com/atom/one-light-ui) and came across to this issue because I saw @simurai closing many issues right now and I wondered why.

I have a question about this migrate:
**How am I enable to continue watch and merge the [`one-light-ui`](https://github.com/atom/one-light-ui) related changes over to my repo?**

For now looks like I have to watch the whole [`atom/atom`](https://github.com/atom/atom) repo because I can't subscribe to a label on GitHub. Even so, probably I need to copy all the changes manually to my repo after this migrate.

Thanks for the help.

**Comment by jasonrudolph** [comment]
> How am I enable to continue watch and merge the one-light-ui related changes over to my repo?

Hi @senki: Could you periodically pull the latest changes from atom/atom and then run `git log packages/one-light-ui` to identify recent changes to the one-light-ui package? Then, if you see a commit that you want to apply to [senki/solarized-one-light-ui](https://github.com/senki/solarized-one-light-ui), I think you could use `git apply -p2` to apply that commit's diff. (In case it helps, you can view the [docs for the `-p` flag here](https://git-scm.com/docs/git-apply#git-apply--pltngt).)

**Comment by jasonrudolph** [comment]
Reopening. I still need to complete the Phase 4 items.

**Comment by jasonrudolph** [comment]
> - [ ] Move all existing issues from the one-light-ui repo to atom/atom using github-issue-mover or a script
> - [ ] Add a label titled packages/one-light-ui to the migrated issues so that they can be found easily

There were no open issues to migrate for one-light-ui, so I omitted these steps when migrating this package.

**Comment by senki** [comment]
Thanks, @jasonrudolph 

unfortunately, it means:
1. now I have a magnitude larger notification  
2. I have to filter all the commits manually
3. apply diffs myself
4. could not attribute commits to the original author (only in the message)

I don't know how my position is unique in the Atom community, but it is a bad deal for me. 😞

**Comment by simurai** [comment]
> @senki I don't know how my position is unique in the Atom community

What is the difference between `solarized-one-light-ui` and `one-light-ui`? Is it mostly the colors and the rest is the same? Something I was thinking, but still have to test if it works in practice: "Forks" could directly import the core files and then override only the variables. Maybe like this:

```less
// solarized-one-light-ui/index.less

// Import one-light-ui variables
@import "/packages/one-light-ui/styles/ui-variables.less";
@import "/packages/one-light-ui/styles/ui-mixins.less";

// Override variables with solarized colors
@import "styles/ui-variables.less";

// Apply overridden variables with styles from one-light-ui
@import "/packages/one-light-ui/styles/atom.less";
@import "/packages/one-light-ui/styles/badges.less";
@import "/packages/one-light-ui/styles/buttons.less";
...
```

Of course you would still have to "watch" for any changes (add/rename/delete) to the custom variables. They get changed rarely, but could still happen.

**Comment by jasonrudolph** [comment]
Hi @senki: I'm sorry that this package consolidation adds more steps to your workflow. 🙁 I wish I knew of a way to achieve the [benefits associated with this change](https://github.com/atom/atom/blob/master/docs/rfcs/003-consolidate-core-packages.md#motivation) without causing any changes on your end.

> could not attribute commits to the original author (only in the message)

Good point. When I [mentioned](https://github.com/atom/atom/issues/17856#issuecomment-415816197) `git apply`, I wasn't aware that you'd want to retain commit authorship, but that totally makes sense. Here's a way that you could consider retaining commit authorship:

1. Add atom/atom as a remote in your local clone of https://github.com/senki/solarized-one-light-ui:

        git remote add upstream https://github.com/atom/atom.git

2. Periodically fetch the latest changes from atom/atom:

        git fetch upstream

3. Identify recent changes to one-light-ui:

        $ git log upstream/master -- packages/one-light-ui
        8ac9919a0 Bump up border size (Somebody, 17 minutes ago)
        3bf4d226e Remove obsolete build status link in one-light-ui README (Jason Rudolph, 3 days ago)

    For example purposes, I've created commit `8ac9919a0` that makes a change to one-light-ui:

        $ git show --format=full 8ac9919a0
        commit 8ac9919a0f46ee23c21304a7e2c76ae993b33a96 (upstream/tmp)
        Author: Somebody <somebody@example.com>
        Commit: Somebody <somebody@example.com>

            Bump up border size

        diff --git a/packages/one-light-ui/styles/panes.less b/packages/one-light-ui/styles/panes.less
        index 1842937ee..b98e26130 100644
        --- a/packages/one-light-ui/styles/panes.less
        +++ b/packages/one-light-ui/styles/panes.less
        @@ -3,8 +3,8 @@ atom-pane-container {

           atom-pane {
             position: relative;
        -    border-right: 1px solid @base-border-color;
        -    border-bottom: 1px solid @base-border-color;
        +    border-right: 2px solid @base-border-color;
        +    border-bottom: 2px solid @base-border-color;

             .item-views {
               // prevent atom-text-editor from leaking ouside might improve performance

4. For each commit you want to bring into solarized-one-light-ui, use [`git format-patch`](https://git-scm.com/docs/git-format-patch) in conjunction with [`git am`](https://git-scm.com/docs/git-am):

        $ git format-patch -1 --stdout 8ac9919a0f46ee23c21304a7e2c76ae993b33a96 | git am -p3

        $ git show --format=full
        commit b7c131da06eedf897c3f5a4ca17b9e0d8dd3641d (HEAD -> master)
        Author: Somebody <somebody@example.com>
        Commit: Jason Rudolph <jason@jasonrudolph.com>

            Bump up border size

        diff --git a/styles/panes.less b/styles/panes.less
        index 1842937ee..b98e26130 100644
        --- a/styles/panes.less
        +++ b/styles/panes.less
        @@ -3,8 +3,8 @@ atom-pane-container {

           atom-pane {
             position: relative;
        -    border-right: 1px solid @base-border-color;
        -    border-bottom: 1px solid @base-border-color;
        +    border-right: 2px solid @base-border-color;
        +    border-bottom: 2px solid @base-border-color;

             .item-views {
               // prevent atom-text-editor from leaking ouside might improve performance

I acknowledge that this is more steps than your previous workflow, but I hope this helps at least a little bit.
