### ISSUE TITLE
Iteration Plan: August 20 - August 31

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#17910]
This is the two-week development plan for Atom for **August 20 - August 31, 2018.**

### :atom: Atom Core

- [x] Fix build issues preventing [`node-pathwatcher`](https://github.com/atom/node-pathwatcher) from building against Node 10 on Windows (https://github.com/atom/node-pathwatcher/pull/126)
- [x] Enable repo-local core packages in the 'packages' folder (https://github.com/atom/atom/pull/17686)
- [x] Upgrade to tree-view 0.224.0 (https://github.com/atom/atom/pull/17088)
- [x] Fix issue where command palette closes if you click on the palette's scrollbar (https://github.com/atom/atom/issues/17236)
- [x] Investigate option to disable discrete GPU (https://github.com/atom/atom/issues/17694)
- [ ] Fix build issues preventing [`cached-run-in-this-context`](https://github.com/atom/cached-run-in-this-context) from working on Node 10 / Electron 3
- [ ] Determine how to handle macOS Mojave Beta issue that causes Atom to need access to Contacts and Calendars (https://github.com/atom/atom/issues/17687)
- [x] Migrate core package 'about' into Atom repo (https://github.com/atom/atom/issues/17832)
- [x] Migrate core package 'one-light-ui' into Atom repo (https://github.com/atom/atom/issues/17856)
- [x] Write the release notes for Atom 1.30.0 and 1.31.0-beta0
- [x] Write the blog post for Atom 1.30.0 and 1.31.0-beta0
- [x] Ship Atom 1.30.0 and 1.31.0-beta0

### :deciduous_tree: Tree-sitter

- [x] Publish docs for Tree-sitter grammar API(https://github.com/atom/flight-manual.atom.io/issues/478)
- [x] Resolve issue with unexpected quote marks when using Tree-sitter in combination with toggle-quotes (atom/toggle-quotes#61)
- [x] Support a single scope name field on Tree-sitter grammars (https://github.com/atom/atom/pull/17881)
- [ ] Turn on tree-sitter by default (https://github.com/atom/atom/issues/17810)

[Previous Iteration](https://github.com/atom/atom/issues/17808)

**Comment by asheren** [comment]
new iteration plan: https://github.com/atom/atom/issues/17984
