### ISSUE TITLE
Iteration Plan: September 4 - September 14

### ISSUE THREAD

**Issue by asheren** [atom/atom#17984]
This is the two-week development plan for Atom for **August 20 - August 31, 2018.**

### :atom: Atom Core

- [ ] Fix flaky KeyBindingResolverView tests (https://github.com/atom/keybinding-resolver/issues/60)
- [ ] Selection changed after clicking 'Find All' with "Only In Selection" enabled (https://github.com/atom/find-and-replace/issues/1034)
- [ ] Migrate core package 'one-light-syntax' into Atom repo (https://github.com/atom/atom/issues/17855)
- [ ] Determine how to handle macOS Mojave Beta issue that causes Atom to need access to Contacts and Calendars (https://github.com/atom/atom/issues/17687)
- [ ] Support `atom` protocol links when links are handled (https://github.com/atom/atom/pull/16940)
- [ ] WIP: Update NuGet submodule and add test for double-digit prerelease sorting (https://github.com/Squirrel/Squirrel.Windows/pull/1353)
- [ ] Migrate core package 'one-dark-syntax' into Atom repo (https://github.com/atom/atom/issues/17853)
- [ ] Come up with 3 measurable results (can build off each other) related to communications and process.
- [ ] Right Clicking Creates a Different Type of Text Selection (https://github.com/atom/atom/issues/17799)
- [ ] Migrate core package 'one-dark-ui' into Atom repo (https://github.com/atom/atom/issues/17854)
- [ ] Go through staff todo lists on atomic reactor board
- [ ] Investigate level of effort for Use newer CDN endpoint (https://github.com/atom/atom.io/issues/164)
- [ ] Migrate core package 'git-diff' into Atom repo (https://github.com/atom/atom/issues/17843)
- [ ] Identify 3 aspects of issue/PR triage that would be useful to automate
- [ ] Migrate core package 'autoflow' into Atom repo (https://github.com/atom/atom/issues/17833)
- [ ] Fix: Added capturing to keydown events when hiding tooltips (https://github.com/atom/atom/pull/17958)

### :deciduous_tree: Tree-sitter
- [ ] Turn on tree-sitter by default (https://github.com/atom/atom/pull/17879)

[Previous Iteration](https://github.com/atom/atom/issues/17910)

**Comment by asheren** [comment]
New Iteration Plan: https://github.com/atom/atom/issues/18187
