### ISSUE TITLE
Iteration Plan: October 1 - October 12

### ISSUE THREAD

**Issue by asheren** [atom/atom#18187]
This is the two-week development plan for Atom for **October 1 - October 12, 2018.**

### :atom: Atom Core

- [x] 1.32.0-beta0 replaced open files with empty untitled files after the update (https://github.com/atom/atom/issues/18124)
- [x] Migrate core package 'deprecation-cop' into Atom repo (https://github.com/atom/atom/issues/17839)
- [x] Migrate core package 'dalek' into Atom repo (https://github.com/atom/atom/issues/17838)
- [x] Determine how to handle macOS Mojave issue that causes Atom to need access to Contacts and Calendars (https://github.com/atom/atom/issues/17687)
- [x] Let's identify aspects of issue/PR triage that would be useful to automate (https://github.com/atom/issue-triage/issues/56)
- [x] Migrate core package 'base16-tomorrow-light-theme' into Atom repo (https://github.com/atom/atom/issues/17837)
- [x] Migrate core package 'base16-tomorrow-dark-theme' into Atom repo (https://github.com/atom/atom/issues/17836)
- [ ] Updating Atom takes more than one "Restart and Install..." click (macOS) (https://github.com/atom/atom/issues/17976)
- [ ] Data loss after power outage (https://github.com/atom/atom/issues/11406)
- [x] Issues sometimes closed without comment (https://github.com/probot/no-response/issues/24)
- [ ] Go through staff todo lists on atomic reactor board
- [ ] Define criteria for when a PR is "reviewable" & do capacity planning to determine what a realistic SLA could be
- [ ] Define our goals & priorities when it comes to reacting to issues, triaging them, prioritizing them, and ultimately resolving them

[Previous Iteration](https://github.com/atom/atom/issues/17984)
