### ISSUE TITLE
Iteration Plan: October 15 - October 26

### ISSUE THREAD

**Issue by asheren** [atom/atom#18237]
This is the two-week development plan for Atom for **October 15 - October 26, 2018.**

### :atom: Atom Core

- [ ] Updating Atom takes more than one "Restart and Install..." click (macOS) (https://github.com/atom/atom/issues/17976)
- [ ] Data loss after power outage (https://github.com/atom/atom/issues/11406)
- [ ] Go through staff todo lists on atomic reactor board
- [ ] Define criteria for when a PR is "reviewable" & do capacity planning to determine what a realistic SLA could be
- [ ] Define our goals & priorities when it comes to reacting to issues, triaging them, prioritizing them, and ultimately resolving them
- [ ] Publish an internal document that defines our issue triage flow and SLA
- [ ] Discuss and determine maximum number of items that can be in the reactive backlog
- [ ] Use the new triage flow in at least one reactive meeting 
- [ ] Go through current backlog in the Reactor Queue and note if all issues are still issues 
- [ ] Migrate core package 'go-to-line' into Atom repo (https://github.com/atom/atom/issues/17844)
- [ ] Migrate core package 'line-ending-selector' into Atom repo (https://github.com/atom/atom/issues/17847)
- [ ] Migrate core package 'grammar-selector' into Atom repo (https://github.com/atom/atom/issues/17845) 
- [ ] feat(ruby.cson) support quoted heredoc literals (https://github.com/atom/language-ruby/pull/212)
- [ ] Spaces are rendering after soft line breaks rather than before (https://github.com/atom/atom/issues/18195) 
- [ ] Escape regex properly (https://github.com/atom/language-python/pull/275)

[Previous Iteration](https://github.com/atom/atom/issues/18187)
