### ISSUE TITLE
Migrate core package 'solarized-light-syntax' into Atom repo

### ISSUE THREAD

**Issue by daviwil** [atom/atom#18281]
This issue tracks the steps necessary to migrate the [`solarized-light-syntax`](https://github.com/atom/solarized-light-syntax) package into the core `atom/atom` repository under the `packages` path:

### Phase 1 - Prepare repo for migration

- [x] Merge or close existing pull requests on the [`atom/solarized-light-syntax`](https://github.com/atom/solarized-light-syntax) repository

Some guidelines for merging vs closing PRs:

- **Merge** when the PR is small, useful, has no merge conflicts with `master`, and has passing tests
- **Close** when the changes are non-trivial, the PR has conflicts with `master`, or there are failing tests in CI

If you close a PR, let the user know that we are currently moving the repository over to `atom/atom` so they should feel free to reopen the pull request there once the package code has been migrated.

### Phase 2 - Migrate the package code

- [x] Create a fresh branch off `master` in your local clone of `atom/atom` with the name `migrate-solarized-light-syntax-package`
- [x] Delete Atom's `node_modules`, `script/node_modules`, and `apm/node_modules` folders if they exist
- [x] Make sure Atom's `package-lock.json` file is unmodified, use `git checkout -- package-lock.json` if it isn't
- [x] Clone the [`atom/solarized-light-syntax`](https://github.com/atom/solarized-light-syntax) repo into the `packages` path of your local Atom repository and then delete its `.git` subfolder
- [x] Delete any unnecessary repo configuration files in the `packages/solarized-light-syntax` folder like `appveyor.yml`, `.travis.yml`, `ISSUE_TEMPLATE.md`, and `PULL_REQUEST_TEMPLATE.md`
- [x] Remove any information from the package's `README.md` which will be inaccurate after the migration is complete (e.g. CI status badges or contribution instructions)
- [x] Open `packages/solarized-light-syntax/package.json` and change the `repository` field to point to the main repo URL `https://github.com/atom/atom`
- [x] Open Atom's `package.json` file to change the following:
  - [x] Update the `solarized-light-syntax` entry in `packageDependencies` to reflect the local path of the package:
    ```
    "solarized-light-syntax": "file:./packages/solarized-light-syntax",
    ```
  - [x] Delete the `solarized-light-syntax` entry in the `dependencies` section since it may contain a hardcoded tarball link.  This will help avoid issues in the next step
- [x] Open `packages/README.md` and perform the following edits:
  - [x] Update the second column of the **solarized-light-syntax** row to reflect the new local path for the package:
    ```
    [`./solarized-light-syntax`](./solarized-light-syntax)
    ```
  - [x] Delete the following line toward the end of the file:
    ```
    [solarized-light-syntax]: https://github.com/atom/solarized-light-syntax
    ```
- [x] Run a full Atom build using `script/build` and verify that there are no unexpected build errors
- [x] Commit the migrated package code and any changes to Atom's `package-lock.json` files to your branch using this commit message:
  ```
  :arrow_right: Migrate core package 'solarized-light-syntax' into ./packages
  ```

### Phase 3 - Make sure the package works and send a PR

- [x] Launch the Atom binary in the `./out` folder and manually verify that the migrated package is working without any obvious issues.  For example, if you're migrating a color theme, turn on that theme to make sure that it changes the editor colors as expected.
- [x] Open the Chrome Developer Tools console (<kbd>Ctrl+Shift+I</kbd> or <kbd>Cmd+Option+I</kbd>) and ensure that there are no errors written there.  If there are, add them to this issue and investigate.
- [x] Create a PR against `atom/atom` with the title "➡ Migrate core package 'solarized-light-syntax' into ./packages".  For convenience, you may use the following message in your PR body:
  ```
  ### Description of the Change

  This PR migrates the core [`solarized-light-syntax`](https://github.com/atom/solarized-light-syntax) package into `atom/atom`.  See issue #18281 for more information.
  ```
- [x] If any CI tests fail, investigate and fix the failures until CI goes green
- [x] Once CI is clean and the PR is approved, merge it

### Phase 4 - Archive the [`solarized-light-syntax`](https://github.com/atom/solarized-light-syntax) repo

- [x] Move all existing issues from the  [`solarized-light-syntax`](https://github.com/atom/solarized-light-syntax) repo to `atom/atom` using [github-issue-mover](https://github-issue-mover.appspot.com/) or a script
- [x] Add a label titled `packages/solarized-light-syntax` to the migrated issues so that they can be found easily
- [x] Edit the original package repo's README.md (don't commit directly) to point contributors to the code's new home in `atom/atom`.  You can use the following text:
  ```
  ### This package is now a part of the [core Atom repository](https://github.com/atom/atom/tree/master/packages/solarized-light-syntax), please direct all issues and pull requests there in the future!

  ---
  ```
- [x] Send a PR to the [`solarized-light-syntax`](https://github.com/atom/solarized-light-syntax) repository with the updated README.md so that watchers will be notified of the change.  You do not need to wait for reviews, it can be merged immediately.  You can use the following PR description text:
  ```
  As of **INSERT MIGRATION PR LINK**, the `solarized-light-syntax` package is now a part of the core Atom repository. This pull request updates `README.md` to reflect that fact. We'll be archiving this repository shortly.

  /cc atom/atom#18281
  ```
- [x] Archive the package repository by going to its [Settings page](https://github.com/atom/solarized-light-syntax/settings), scroll down to the "Danger Zone" section and click "Archive this Repository"

Migration is now complete! :tada:

**Comment by ryanolsonx** [comment]
I've created a PR that accomplishes phases 1-3. Once that PR is merged, I'll need someone to do phase 4, as I don't have control of the solarized-light-syntax repo.
