### ISSUE TITLE
Iteration Plan: November 13 - November 21

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#18431]
This is the two-week development plan for Atom for October 26 - November 9, 2018.

* [x] [Missing documentation](https://github.com/atom/atom/issues/18308)
* [x] [Uncaught error: adding a pane item with a URI](https://github.com/atom/tabs/issues/444)
* [ ] [Tag matching doesn't work in HTML with Tree-sitter enabled](https://github.com/atom/bracket-matcher/issues/355)
* [ ] [Atom 1.32 does not inherit environment variables when not launched from the command line](https://github.com/atom/atom/issues/18318)

[Previous Iteration](https://github.com/atom/atom/issues/18368)
