### ISSUE TITLE
Iteration Plan: November 26 - December 7

### ISSUE THREAD

**Issue by asheren** [atom/atom#18504]
This is the two-week development plan for Atom for November 26 - December 7, 2018.

- [ ] Ship v0.1 of automation to add all new issues to the Triage Inbox
- [ ] [Migrate 'atom-ui' into core](https://github.com/atom/atom/pull/18484)
- [ ] [atom.config.set will erase settings when scopeSelector is "*"](https://github.com/atom/atom/issues/18372)
- [ ] [Automatically redirect HTTP to HTTPS](https://github.com/atom/blog.atom.io/issues/241)
- [ ] [Incorrect highlighting for numbers with decimal point, e, B and D](https://github.com/atom/language-ruby/issues/251)
- [ ] For every ticket accomplished, the team will also review one triage PR that is ready to review

[Previous Iteration](https://github.com/atom/atom/issues/18431)
