### ISSUE TITLE
Iteration Plan: January 24 - February 1, 2019

### ISSUE THREAD

**Issue by asheren** [atom/atom#18751]
This is the development plan for Atom for January 24 - February 1, 2019.

- [x] [Unable to open project directory while it's removed](https://github.com/atom/atom/issues/16645)
- [x] [Unable to manually update Atom with `Automatically Update` disabled](https://github.com/atom/atom/issues/18559)
- [x] Continue conversations to identify what can be improved in order to improve startup time
- [ ] For every ticket accomplished, the team will also review one triage PR that is ready to review
- [x] Finish work to upgrade to Electron 3.0
- [ ] [Default to @atom/watcher](https://github.com/atom/atom/pull/17899)
- [x] [Updating Atom takes more than one "Restart and Install..." click (macOS)](https://github.com/atom/atom/issues/17976)
- [ ] Atom Flight Manual audit 
- [ ] Convert Atom Flight Manual code examples to JavaScript

[Previous Iteration](https://github.com/atom/atom/issues/18572)

**Comment by daviwil** [comment]
Next iteration plan: https://github.com/atom/atom/issues/18823

**Comment by oskarkrawczyk** [comment]
> * Finish work to upgrade to Electron 3.0

I was wondering, is there an official policy on the Electron upgrade cycle in Atom? 

Couldn't not notice Atom is quite behind the current Electron version, and it seems it'll be even more behind once 5.0 hits.

The reason I'm asking is because of some new API's added to Electron, `getColor` to be more specific, which would allow themes to fit the dark mode tint on macOS.

Thanks for all the fantastic work!
