### ISSUE TITLE
Iteration Plan: February 4 - February 15, 2019

### ISSUE THREAD

**Issue by daviwil** [atom/atom#18823]
This is the development plan for Atom for February 4 - February 15.

- [ ] Finish the RFC for improved Atom state management (https://github.com/atom/atom/pull/18700)
- [ ] Improve CI build stability
- [x] Identify more possible startup time improvements via profiling ([`startup-time` label](https://github.com/atom/atom/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22startup-time%22+))
- [x] Convert Flight Manual CoffeeScript examples to JavaScript
- [x] Complete the Flight Manual audit
- [x] [Python-elif and else not folding](https://github.com/atom/language-python/issues/290)
- [x] [CSS grammar not injected for custom styled-components](https://github.com/atom/language-javascript/issues/634)
- [x] [Unable to edit text in search field after toggling search](https://github.com/atom/find-and-replace/issues/1067)
- [ ] [Wrong hint when jumping to the column of a line](https://github.com/atom/fuzzy-finder/issues/363)

[Previous Iteration](https://github.com/atom/atom/issues/18751)

**Comment by smashwilson** [comment]
Next iteration: #18889.
