### ISSUE TITLE
Iteration Plan: February 25 - March 11, 2019

### ISSUE THREAD

**Issue by smashwilson** [atom/atom#18889]
This is the development plan for Atom for February 25 - March 11.

- [ ] Investigate the feasibility of dropping back to Electron 2.x for the moment
- [ ] Atom Nightly 1.37.0-nightly0 crashing [#18840](https://github.com/atom/atom/issues/18840)
- [ ] Renderer process crash in tests [#18790](https://github.com/atom/atom/issues/18790)
- [ ] GUI disappears while process uses all CPU [#18841](https://github.com/atom/atom/issues/18841)
- [ ] [Wrong hint when jumping to the column of a line](https://github.com/atom/fuzzy-finder/issues/363)

[Previous Iteration](https://github.com/atom/atom/issues/18823)
