### ISSUE TITLE
Iteration Plan: March 4 - March 15, 2019

### ISSUE THREAD

**Issue by asheren** [atom/atom#18955]
This is the development plan for Atom for March 4 - March 15, 2019.
- [ ] [Update TextEditor styles when changing language mode](https://github.com/atom/atom/pull/18888)
- [x] [copied keybinding with single quote should be escaped](https://github.com/atom/settings-view/issues/1110)
- [ ] [Slow startup for large projects](https://github.com/atom/fuzzy-finder/issues/271)
- [ ] [Use server repository instead of package defined](https://github.com/atom/settings-view/pull/1119)
- [ ] [Problems with multiple languages on Windows 10](https://github.com/atom/node-spellchecker/issues/109)
- [ ] [Atom built from source (v1.34) crashes when opening a folder with git repository](https://github.com/atom/atom/issues/18926)
- [ ] Create discrete tasks for quarterly work

Previous Iteration: https://github.com/atom/atom/issues/18889

**Comment by asheren** [comment]
next iteration plan: https://github.com/atom/atom/issues/19011
