### ISSUE TITLE
Try upgrading libgit2 to resolve renderer crashes

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#19007]
As a potential resolution for the libgit2 crashes in https://github.com/atom/atom/issues/18990, let's upgrade to a newer version of libgit2.

### Background

As described in https://github.com/atom/atom/issues/18990#issuecomment-474078139, many of the build failures reported in https://github.com/atom/atom/issues/18990 are due to a crash happening inside libgit2.

For example, in [this build](https://github.visualstudio.com/Atom/_build/results?buildId=34137), the tree-view tests fail due to a renderer crash [here](https://github.visualstudio.com/Atom/_build/results?buildId=34137&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=bde16fc7-7659-5b1c-12aa-0110866d993c&lineStart=2789&lineEnd=2790&colStart=1&colEnd=1), and the build artifacts include a crash report in the `crash-reports.zip` file [here](https://github.visualstudio.com/_apis/resources/Containers/1160191?itemPath=crash-reports.zip%2FAtom%20Dev%20Helper_2019-02-26-204525_Mac-345.crash). The crash report points to code inside libgit2:

```
...
Crashed Thread:        17
...
Thread 17 Crashed:
0   libsystem_c.dylib             	0x00007fff68f39232 strlen + 18
1   libsystem_c.dylib             	0x00007fff68f7da86 __vfprintf + 4716
2   libsystem_c.dylib             	0x00007fff68fa5059 __v2printf + 473
3   libsystem_c.dylib             	0x00007fff68f8a34b _vsnprintf + 415
4   libsystem_c.dylib             	0x00007fff68f8a3fe vsnprintf + 80
5   git.node                      	0x0000000112a22697 git_buf_vprintf + 183 (buffer.c:387)
6   git.node                      	0x0000000112a3c8b9 giterr_set + 203 (errors.c:56)
7   git.node                      	0x0000000112a63477 git_path_diriter_next + 164 (path.c:1316)
8   git.node                      	0x0000000112a4fc5c fs_iterator__expand_dir + 577 (iterator.c:1256)
9   git.node                      	0x0000000112a4df8c fs_iterator__advance_into + 75 (iterator.c:1434)
10  git.node                      	0x0000000112a32f73 git_diff__from_iterators + 3078 (iterator.h:181)
11  git.node                      	0x0000000112a33c45 git_diff_index_to_workdir + 325 (diff.c:1397)
12  git.node                      	0x0000000112a7a0c5 git_status_list_new + 833 (status.c:344)
13  git.node                      	0x0000000112a7a661 git_status_foreach_ext + 41 (status.c:424)
14  git.node                      	0x0000000112a19760 StatusWorker::Execute() + 106 (repository.cc:361)
15  libnode.dylib                 	0x00000001071d6d0e 0x107029000 + 1760526
16  libnode.dylib                 	0x00000001071d707f 0x107029000 + 1761407
17  libsystem_pthread.dylib       	0x00007fff69201661 _pthread_body + 340
18  libsystem_pthread.dylib       	0x00007fff6920150d _pthread_start + 377
19  libsystem_pthread.dylib       	0x00007fff69200bf9 thread_start + 13
```

If we can resolve these crashes, we can eliminate a major source of the build instability that we're experiencing.

### Proposed improvement: Upgrade to newer version of libgit2

atom/atom is using an old version of libgit2 ([v0.24.3](https://github.com/libgit2/libgit2/releases/tag/v0.24.3)) from November 2016. The error is happening in a [portion of the libgit2 code](https://github.com/libgit2/libgit2/blob/v0.24.3/src/iterator.c#L1349-L1394) that doesn't even exist in the current version of libgit2 ([v0.28.1](https://github.com/libgit2/libgit2/releases/tag/v0.28.1)).

We briefly tried using a never version of libgit2 last year, but we [reverted](https://github.com/atom/atom/commit/12875c19395224da980485e7dc2581a60b57ef76) that change due to a [performance regression](https://github.com/libgit2/libgit2/issues/4740) in libgit2. The performance regression was fixed in https://github.com/libgit2/libgit2/pull/4809, so I think we can try upgrading again. It's possible that the upgrade would prevent these crashes.

### TODO

- [x] Upgrade atom/git-utils to a version of libgit2 that includes the [fix for the performance regression](https://github.com/libgit2/libgit2/pull/4809)
- [x] Upgrade atom/atom to use that newer version of libgit2
- [x] Kick off at least 10 CI builds on Azure DevOps and verify that none of them result in crashes inside libgit2

**Comment by rafeca** [comment]
> Upgrade atom/git-utils to a version of libgit2 that includes the fix for the performance regression

Done! [`git-utils@5.5.0`](https://github.com/atom/git-utils/releases/tag/v5.5.0) was published with the fix.

> Upgrade atom/atom to use that newer version of libgit2

Pull Request with the upgrade: https://github.com/atom/atom/pull/19021

> Kick off at least 10 CI builds on Azure DevOps and verify that none of them result in crashes inside libgit2

List of builds:

1. ⏳https://github.visualstudio.com/Atom/_build/results?buildId=36205

**Comment by rafeca** [comment]
Build number 12 resulted in a crash 😢

The crash this time happened in Windows X64, this is both good and bad news:

* It's good news because the flakiness reported in https://github.com/atom/atom/issues/18990 was related to MacOS, so this issue may be unrelated to that one (or even to `libgit2`).
* It's bad news because unfortunately our Azure pipelines are not currently storing the crash reports for Windows, so we're currently blind about this issue... It may be related to `libgit2` or it may not...

**Comment by rafeca** [comment]
Ok, just found that we had renderer process crashes on Window X64 before: https://github.com/atom/atom/issues/18991, so it's probable that the crash has not have been introduced in this PR (but we cannot rule out that the crash is related to `libgit2` without a crash log).

**Comment by jasonrudolph** [comment]
@rafeca: Quick question for you: Can you help me understand what the "stable" column means in https://github.com/atom/atom/issues/19007#issuecomment-475176641?

**Comment by rafeca** [comment]
> @rafeca: Quick question for you: Can you help me understand what the "stable" column means in #19007 (comment)?

It means that there were no renderer crashes on CI, I'm gonna rename it to `Crash-free`, which may be more clear 😅

**Comment by rafeca** [comment]
@jasonrudolph I've done 20 builds and I think that except the JS test failure in the Text Component, I've seen all the other randomly happening on the repo before this PR (including the timeout in the fuzzy finder, which would look like suspicious).

What do you think about the results?

**Comment by jasonrudolph** [comment]
> What do you think about the results?

This looks super promising, @rafeca. I'm cautiously optimistic that #19021 has resolved these crashes. I think we should close this issue and keep an eye out for any sign of these crashes in future builds.
