### ISSUE TITLE
Iteration Plan: March 18 - March 29, 2019

### ISSUE THREAD

**Issue by asheren** [atom/atom#19011]
This is the development plan for Atom for March 18 - April 1, 2019.

- [ ] [Log the time it takes to index the project](https://github.com/atom/fuzzy-finder/issues/371)
- [ ] Start work on a new helpful bot
- [ ] [Try upgrading libgit2 to resolve renderer crashes](https://github.com/atom/atom/issues/19007)
- [ ] Start work to streamline Atom documentation
- [ ] [atom.config.set will erase settings when scopeSelector is "*"](https://github.com/atom/atom/issues/18372)
- [ ] [[Atom 1.32.0] Does not inherit environment variables when launched not from the command line](https://github.com/atom/atom/issues/18318)
- [ ] [Nonoptimal CI build / lint ordering](https://github.com/atom/atom/issues/18940)
- [ ] [[macOS] File->Reopen Project does not work when there are no open windows](https://github.com/atom/atom/issues/17530)

Previous Iteration: https://github.com/atom/atom/issues/18955

**Comment by xthdraft** [comment]
Is electron 2.0.18 in the current version of atom? Any timeline for integrating electron v3.0.6 and later into atom?

**Comment by 50Wliu** [comment]
> Is electron 2.0.18 in the current version of atom?

Yes.

> Any timeline for integrating electron v3.0.6 and later into atom?

No timeline, but you can track progress at #18916.
