### ISSUE TITLE
Iteration Plan: April 1 - April 12, 2019

### ISSUE THREAD

**Issue by asheren** [atom/atom#19104]
This is the development plan for Atom for April 1 - April 12, 2019.

- [ ] [Nonoptimal CI build / lint ordering](https://github.com/atom/atom/issues/18940)
- [ ] Finish work on a new helpful bot
- [ ] [Show prompt to enable "fast mode" on large projects](https://github.com/atom/fuzzy-finder/issues/376)
- [ ] Continue work to streamline Atom documentation
- [ ] Start organizing a possible Atom contributors mixer at an upcoming conference
- [ ] [Flaky build: Core main process tests sometimes fail with "Object has been destroyed"](https://github.com/atom/atom/issues/19089)
- [ ] [[Atom 1.32.0] Does not inherit environment variables when launched not from the command line](https://github.com/atom/atom/issues/18318)
- [ ] [Chapter 1 cleanup notes](https://github.com/atom/flight-manual.atom.io/issues/514)
- [ ] [Flaky build: Windows build sometimes fails with "resource busy or locked"](https://github.com/atom/atom/issues/18991)

Previous Iteration: https://github.com/atom/atom/issues/19011
