### ISSUE TITLE
Iteration Plan: April 15 - April 26, 2019

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#19170]
This is the development plan for Atom for April 15 - April 26, 2019.

- [x] Opening a file opens in a new window (https://github.com/atom/atom/issues/19147)
- [x] `File > Reopen Project` adds the project as a folder to the current window on Windows and Linux, doesn't work on macOS (https://github.com/atom/atom/issues/19149)
- [x] Re-open Atom File Not Exists (but actually exists) & can't Reopen Project (https://github.com/atom/atom/issues/19146)
- [ ] Flaky build: Windows build sometimes fails with "resource busy or locked" (https://github.com/atom/atom/issues/18991)
- [x] Flaky build: Windows builds failing even when all tests are passing (https://github.com/atom/atom/issues/19089)
- [x] Programmatically calling pane.activate() does not update its isFocused() state (https://github.com/atom/atom/issues/18913)
- [x] Uncaught TypeError: Cannot read property 'incrementCounter' of undefined (https://github.com/atom/fuzzy-finder/issues/380)
- [x] Last table cell isn't displayed if it doesn't have any data (https://github.com/atom/markdown-preview/issues/206)
- [x] Heredoc strings no longer syntax highlighted (https://github.com/atom/language-ruby/issues/249)
- [x] Chapter 2 cleanup notes (https://github.com/atom/flight-manual.atom.io/issues/515)
- [ ] Continue work to streamline Atom documentation
- [ ] Continue organizing a possible Atom contributors mixer at an upcoming conference

Previous Iteration: https://github.com/atom/atom/issues/19104
