### ISSUE TITLE
Iteration Plan: April 29 - May 10, 2019

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#19236]
This is the development plan for Atom for April 29 - May 10, 2019.

* [x] Flaky build: Windows build sometimes fails with "resource busy or locked" (#18991)
* [x] Flaky test: WorkspaceElement mousing over docks ... shows the toggle button when the dock is open (#18992)
* [x] Flaky build: atom-application test sometimes fails on Linux (#19235)
* [ ] Improve time to find on a large repository by using `ripgrep` (https://github.com/atom/find-and-replace/issues/1075)
* [ ] Editor hangs/freeze with open a big (~4MB) file that only have a single long line (#14952)
* [x] Flaky build: AppVeyor build sometimes fails due to problems uploading JUnit XML (#18994)
* [ ] macOS: cmd+backtick stopped working between 1.35.1 and 1.36.0 (#19168)
* [x] when opening a file with a line number, atom should scroll down to display that line number at the top of the view (#12253)
* [x] shellscript TextMate grammar incorrectly tokenizes here doc (https://github.com/atom/language-shellscript/issues/139)

Previous iteration: #19170
