### ISSUE TITLE
Iteration Plan: May 13 - May 24, 2019

### ISSUE THREAD

**Issue by asheren** [atom/atom#19327]
This is the development plan for Atom for May 13 - May 24, 2019.

- [ ] [Ask for root password when required](https://github.com/atom/atom/issues/4115)
- [ ] [First context menu to be opened after Atom starts closes on its own](https://github.com/atom/atom/issues/19308)
- [ ] [aliases(?) on components in JSX cause the jsx block to be highlighted incorrectly](https://github.com/atom/language-typescript/issues/34)
- [x] Start work on Electron 3 upgrade
- [x] [Prompts for restart when @atom/notify watcher not selected](https://github.com/atom/atom/issues/19323)
- [x] [Atom 1.39.0-nightly1 fails to open](https://github.com/atom/atom/issues/19320)
- [x] [Improve time to find on a large repository by using `ripgrep`](https://github.com/atom/find-and-replace/issues/1075)
- [ ] Improving Atom FAQ
- [ ] Centralizing Flight Manual documentation

Previous Iteration: https://github.com/atom/atom/issues/19236
