### ISSUE TITLE
Iteration Plan: May 27 - June 7, 2019

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19417]
This is the development plan for Atom for May 27 - June 7, 2019.

- [x] [Change the telemetry storage to maintain metrics between sessions](https://github.com/atom/telemetry/issues/26).
- [x] [Investigate faster CI builds](https://github.com/atom/atom/issues/19366).
- [x] [Flaky test: Timeout in test "toggling when the project ...."](https://github.com/atom/fuzzy-finder/issues/386).
- [x] [View > Panes doesn't show keybindings in menu](https://github.com/atom/atom/issues/5343).
- [x] ["Replace All - Within Current Selection" only replaces a single match](https://github.com/atom/find-and-replace/issues/1010).
- [x] [Atom 1.37.0 does not properly track (grey out) `**` in .gitignore](https://github.com/atom/tree-view/issues/1317).
- [x] Startup time: spike of a day to try to find some low hanging fruit that can improve startup time by at least 5%.
- [x] Get the Electron 3 upgrade finally merged.
- [ ] Improving Atom FAQ.
- [ ] Centralizing Flight Manual documentation.

Previous Iteration: #19327
