### ISSUE TITLE
Iteration Plan: June 10 - June 21, 2019

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19484]
This is the development plan for Atom for June 10 - June 21, 2019.

- [x] [Fix flaky test: test on the `markdown-preview` package times out](https://github.com/atom/atom/issues/19478).
- [x] [Fix flaky test: Provider API test on autocomplete-plus failing](https://github.com/atom/atom/issues/19478).
- [x] Migrate off of AppVeyor for atom/atom.
- [x] Review work remaining on nightly releases and make a decision.
- [x] [Fix "Uncaught TypeError: Cannot read property 'length' of undefined " error](https://github.com/atom/atom/issues/19430).
- [x] [Memory leak & poor performance when using Rust Language Server on Linux](https://github.com/atom/nsfw/issues/7).
- [x] [Cannot fold `match` in Rust](https://github.com/atom/atom/issues/19435).
- [x] [TreeSitterLanguageMode.tokenizedLineForRow appears to have a bug](https://github.com/atom/atom/issues/18973).
- [x] [Document under "Restore previous window on start" that it works only if you add a project folder ](https://github.com/atom/settings-view/issues/1129).

Previous Iteration: #19417
