### ISSUE TITLE
Iteration Plan: June 24 - July 5, 2019

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19593]
This is the development plan for Atom for June 10 - July 5, 2019.

- [ ] Add in alerts to improve our understanding of crashes when releases go out.
- [ ] [Explore potential blockers for Electron v4 upgrade](https://github.com/atom/atom/pull/19373).
- [ ] Deprecate Travis CI builds. Should be easy to do after the CircleCI deprecation.
- [ ] [Side by side installation of Atom versions on Windows](https://github.com/atom/atom/pull/17813).
- [ ] ["Restart and install" closes and updates Atom but doesn't restart on Windows](https://github.com/atom/atom/issues/19493).
- [ ] [Quote character in comment causes auto-indent error](https://github.com/atom/language-javascript/issues/648).
- [ ] [Failed to activate the metrics package](https://github.com/atom/metrics/issues/102).
- [ ] [Flow files no longer have `source.js` scope, snippets broken](https://github.com/atom/language-typescript/issues/29).

Previous Iteration: #19484
