### ISSUE TITLE
Iteration Plan: July 22 - Aug 2, 2019

### ISSUE THREAD

**Issue by asheren** [atom/atom#19721]
This is the development plan for Atom for July 22 - Aug. 2, 2019.

- [ ] [Default array value syntax error with class constants](https://github.com/atom/language-php/issues/363)
- [ ] [Weird color Python subclasses in One Theme](https://github.com/atom/atom/issues/19588).
- [ ] [[nightly] Comment highlighting is leaking](https://github.com/atom/atom/issues/19582)
- [ ] [Shell arithmetic syntax highlight breaks on multiple cases](https://github.com/atom/language-shellscript/issues/148).
- [ ] [Windows with files open but no open project not restored with "Restore previous window on start" ](https://github.com/atom/settings-view/issues/1129).
- [ ] [Inconsistent highlighting of constants](https://github.com/atom/language-ruby/issues/265).
- [ ] [Bash ANSI C like strings with escaped quote breaks syntax highlight](https://github.com/atom/language-shellscript/issues/146).
- [ ] [atom.io API docs missing for a workspace item's optional methods](https://github.com/atom/atom/issues/17746).
- [ ] [Workspace Item API documentation is truncated](https://github.com/atom/atom/issues/16106)
- [ ] [build-package.sh fails to extract deb package with beta channel on Travis CI with Ubuntu Trusty](https://github.com/atom/ci/issues/94)
- [ ] [Build-id link for libffmpeg.so should be removed from RPM](https://github.com/atom/atom/issues/19692)
- [ ] [Oracle Linux 7.6: 1.39.0.beta3: Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found](https://github.com/atom/atom/issues/19682)
- [ ] [Broken package atom-1.39.0-0.1 for CentOS 7](https://github.com/atom/atom/issues/19690)

Previous Iteration: https://github.com/atom/atom/issues/19593

**Comment by ryanolsonx** [comment]
Is this the latest iteration plan?  Are there still any active Github employees working on Atom?

**Comment by lee-dohm** [comment]
@ryanolsonx We stopped posting iteration plans for the time being because our focus right now is on bug fixes. Yes, there are still active GitHub employees working on Atom. We’re re-evaluating how we handle transparency around planning. We’ll share more substantive updates as soon as we can.
