### ISSUE TITLE
Allow panes to be resized

### ISSUE THREAD

**Issue by Caged** [atom/atom#274]
Panels split the difference between the space available.  It'd be nice if we could manually resize them.  Should take a look at what @nakajima did with the tree view.

**Comment by Moter8** [comment]
:+1: @yjw9012 Achieved any progress on this?

**Comment by philipgiuliani** [comment]
http://codepen.io/pprice/pen/splkc/ Here a demo of a resizing flexbox :)

**Comment by 360fun** [comment]
I'm in the waiting queue too: I really need this feature please!!!

In the meanwhile...is there any package that implements it with mouse support? (like in the @philipgiuliani example)

**Comment by davidgilbertson** [comment]
@yjw9012 How are you progressing? I started using Atom yesterday and love it, this feature is the only thing missing for me. I'd like to try and write it myself (specifically, dragging the pane divider to adjust widths), but if you're almost done I shall wait patiently.

**Comment by yjw9012** [comment]
I've been slow on this because I've been super busy searching for a new job. Finally, I just got a new job, and I am planning to spend significant efforts on the issue.

**Comment by prescottprue** [comment]
Thanks @yjw9012 ! It is one of the few things left that are holding back Atom compared to sublime.

**Comment by yjw9012** [comment]
@davidgilbertson 
I am becoming busy again looking for a new apartment in San Francisco. If you want, you can go ahead and try it.

**Comment by rmartin** [comment]
hey @davidgilbertson ,

I'd be interested in teaming up with you on this. This is a feature that i'm strongly interested in as well and have been reviewing the code to potentially resolve this along with ability to split panes https://github.com/atom/atom/issues/4738 . Let me know if you or others would be interested in collaborating on this as hopefully that will allow us to get this added to the core module sooner than later. I think @philipgiuliani codepen example above is a good start along with the file tree pane view that's already in the build. 

Cheers,
Roy

**Comment by Caged** [comment]
Here's the relevant tree-view code - https://github.com/atom/tree-view/blob/47894ce1ebd68ab7c5c02214d945d7674a3fdfaf/lib/tree-view.coffee#L205-L224

**Comment by rmartin** [comment]
Thanks @Caged, I made some good initial progress and got my head wrapped around the tree view and how they added in the resize handler into the tree view. Thanks for the pointer. 

Based on that i've just stubbled out the hooks and logic in LESS using pseudo elements and put the basic structure in place. My goal is to research a little more into how to inject the content elements into the appropriate places in the DOM and swap out the pseudo elements.  Once I get that squared away i'm going to break out the resize with keyboard and resize with mouse into separate scripts and work on getting that refined. 

Thinking through the cases to add the resize handler into the view I think in general the rule I have in there for the CSS selectors is about right. Likely there are some more complex cases I'm not considering, but this looks roughly like this:
* .panes .pane:not(:last-child)::after
* .panes .vertical .pane:not(:first-child)::before

You can follow along in my fork and certainly i'm open to any suggestions / insights into the proper way to take the content elements and inject those into the view/DOM. It might be a little slow going the rest of the week, but I'll try to revisit this where I can and again over the weekend and you can continue to follow along within that repo for progress. 
https://github.com/rmartin/resize-panes/
https://github.com/rmartin/resize-panes/commit/aa2db864e8658956c3af04aeb588952756537d16

Cheers,
Roy

**Comment by rmartin** [comment]
Hi All,

Please find my overall status update below. 

## Summary
I've completed the initial implementation for resizable horizontal panes within my fork branch (https://github.com/rmartin/resize-panes/tree/issue-7-resize-with-mouse). I followed @chriscoyier's CodePen.io approach which he outlined in his blog (http://codepen.io/chriscoyier/blog/design-is-hard). This adds a resizable pane after the appropriate pane's in the editor view and uses a straight-forward (thanks to the write-up) approach for managing this using pixels instead of percentages. 

Demo:
![resize-panes](https://cloud.githubusercontent.com/assets/119151/6224138/e8ae6284-b62b-11e4-863f-4ddb44343592.gif)

## Approach Overview
I experimenting around with several approaches, including adding the resize pane to the editor or inner pane. I found that adding it to the outside of the pane is the most intuitive user experience for adding resize bars. Unfortunately, it's also the most complex case as you need to now maintain a unique pane element. The biggest hurdle was was trying to determine the best way to attach to the PaneAxis classes which are inserted dynamically depending on your panes. I was able to overcome that hurdle today and built a collection that seems to maintain and unload this well. 

Due to the complexity of this approach testing is going to be key. I've gotten the initial base cases complete (split 1,2,3 horizontally). I'm now going to work on writing the tests for all of the various scenarios that are likely to come-up when splitting the panes and opening items. 

## Outstanding Items
Here is a quick summary of the my overall progress that I will work on keeping up to date. 

- [x] Horizontal Resize - Add horizontal resize support. Insert resizable panes Add baseline test cases and fix all standard horizontal pane splits.
- [ ] Horizontal Test Cases - Add test cases for all reasonable scenarios to ensure that panes are loaded as expected. 
- [ ] Vertical Resize - Add vertical resize support and baseline test cases
- [ ] Vertical Test Cases - Add test cases for all reasonable scenarios to ensure that panes are loaded as expected. 
- [ ] Keyboard Support - Add back in the original plugin architecture and update to use new Fluxbox resize pattern
- [ ] 1.0 Prep - Ensure all jQuery references are removed and overall standards are followed for 1.0 prep release. Full details here (https://atom.io/docs/v0.179.0/upgrading/upgrading-your-package)
- [ ] Resize Pane Insert Method - Experiment around with using the insert child method to attach resize panes to the PaneAxis
- [ ] Dispose / Destroy - Current command line tests are showing a warning for destroying view. Add test cases and ensure there are no orphans / memory leaks.
- [ ] Code Audit - Have a code audit by Atom team members to ensure use of best practices. All comments are welcome!

Cheers,
Roy

**Comment by 360fun** [comment]
GREEEEEEEEEAT MAN! :D

**Comment by eddiemonge** [comment]
is the text supposed to wrap? Or do you have that options turned off?

**Comment by rmartin** [comment]
hey @eddiemonge,

That's correct, I don't have 'Soft Wrap' enabled by default. The good news is that this works just fine as all i'm doing is adjusting the Fluxbox widths. You can see an example of this below. 

Soft Wrap Demo:
![resize-panes-soft-wrap](https://cloud.githubusercontent.com/assets/119151/6257028/c166e98e-b771-11e4-8c62-f7d20cd5cff2.gif)

**Comment by eddiemonge** [comment]
awesome, wanted to make sure it supported both cases. cant wait for this (or something like it) to land

**Comment by jglovier** [comment]
@rmartin this is looking :sparkles:!!! Nice work. :heart_eyes:

**Comment by philipgiuliani** [comment]
Really cool @rmartin :) you already have some progress? :)

**Comment by admix** [comment]
That is really nice, was waiting for this feature to be added to Atom... :)

**Comment by planetoftheweb** [comment]
I hope this makes it into Atom soon. I would totally switch over, but I can't stomach panes that are not resizable.

**Comment by wsimmerson** [comment]
+1

**Comment by patrickgilmour** [comment]
+1

**Comment by pitaj** [comment]
I created an addon that adds this functionality to atom. Simply drag the handles between panes to resize them. 

https://github.com/pitaj/atom-resize-panes/

**Comment by lglasgow** [comment]
@pitaj That addon is awesome. Thanks! Pane resizing was the last thing keeping me from switching full time from sublime text.

**Comment by kevinsimper** [comment]
@pitaj Nice, using it right now!

**Comment by jlphelps** [comment]
@pitaj Thank you so much for the plugin, I love it!

**Comment by planetoftheweb** [comment]
Thanks a ton for this. It really makes Atom more usable.

**Comment by philipgiuliani** [comment]
This will finally be in Atom 0.193! :) https://github.com/atom/atom/pull/5902 got merged! :tada:

**Comment by izuzak** [comment]
Thanks for the reminder, @philipgiuliani -- closing this since it was fixed in https://github.com/atom/atom/pull/5902. It will be included in Atom 0.193

**Comment by jglovier** [comment]
![joel-tim-toast](https://cloud.githubusercontent.com/assets/1319791/7183163/d25293a4-e423-11e4-97d3-4eb9970554cd.gif)

**Comment by mmcbride1007** [comment]
:clap: so excited about this!

**Comment by chrishough** [comment]
I noticed this recently broke in the latest version of atom.  I can no longer use cmd+alt-- to shrink or expand windows, thoughts?

**Comment by mnquintana** [comment]
@chrishough What do you mean shrink or expand windows? That sounds unrelated to pane resizing, and I don't recall that keybinding ever doing anything in Atom out of the box – that sounds like a community package.

**Comment by mnquintana** [comment]
@chrishough The keybinding you're referring to was only ever in [resize-panes](https://github.com/santip/resize-panes) – it's not in Atom core.

**Comment by chrishough** [comment]
They used to work with https://github.com/santip/resize-panes @mnquintana but since the latest release broken that package, it looks like they are dead. Also, that functionality can not be installed because core does that now right?

**Comment by chrishough** [comment]
@MasseGuillaume how did you get the new keyboard shortcuts to work?

**Comment by mmcintyre123** [comment]
Hi there, in atom in Ubuntu the tree view and panels still can't be resized.  Can you add that functionality for atom in Ubuntu?

**Comment by mark-hahn** [comment]
> in atom in Ubuntu the tree view and panels still can't be resized.

I'm having no problem in ubuntu 14.04 with Atom 1.0.1.

**Comment by mmcintyre123** [comment]
Hmm I'm in ubuntu 14.04 LTS and atom 1.0.2

**Comment by mmcintyre123** [comment]
Just checked for updates in ubuntu and chrome was the only update.

**Comment by batjko** [comment]
@mmcintyre123 How exactly are you doing the resizing? And do you have that problem also in safe mode (`atom --safe`)?

**Comment by mmcintyre123** [comment]
So I'm using ubuntu in VirtualBox, but I have atom in Windows (host) as well, and the I do it there by just hovering over the right border between the tree pane and the document.  An arrow shows up, then just click and drag.... very straightforward.

In atom I hover over the border between the tree pane and the rest of the window -- I try the same thing for split panes -- and no arrow shows up.  I try clicking and dragging and nothing happens.  It appears the functionality just isn't there or somehow is not recognized in the ubuntu version.

**Comment by mmcintyre123** [comment]
I opened atom in safe mode (verified by icon in bottom left - "this window is in safe mode") and the problem is the same.

**Comment by batjko** [comment]
Yea so there is a known problem with using Atom via Virtual Box, particularly mouse events are often screwed up. 
See this issue: https://github.com/atom/atom/issues/6306

**Comment by mmcintyre123** [comment]
Oh, well that's disappointing.  For onlookers, see 
#7578, #513, #6306
If anyone has a fix or work-around for this it would be much appreciated!

**Comment by RenaKunisaki** [comment]
In v1.10.2 on Arch AMD64 I'm able to drag to resize panes left/right, but not up/down.

**Comment by BRD-E** [comment]
I am still currently unable to do up/down resizing aswell. This would be an awesome feature to add to atom
