### ISSUE TITLE
API Freeze : Atom 1.0-pre

### ISSUE THREAD

**Issue by benogle** [atom/atom#3041]
The goal is to improve the package writing experience and settle on an API we will support through 1.0. This means cleaning up the API, writing better API documentation and redesigning the [API webpage](https://atom.io/docs/api). 

The result of the API freeze will be an solid structure on which we can build. A lot of methods and approaches will be deprecated, but nothing will be removed until we near 1.0. We will be able to _add_ more APIs after the freeze, but will commit to not removing anything until the next major. 

## Tasks

* [x] Remove the non-react editor https://github.com/atom/atom/issues/3040
* [x] Convert all docs to [atomdoc](https://github.com/atom/atomdoc) https://github.com/atom/atom/pull/3229
* [x] Redesign the API Docs http://atom.io/docs https://github.com/github/atom.io/pull/643
* [x] Split API into Essential / Extended
* [x] Convert all events to event methods (http://blog.atom.io/2014/09/16/new-event-subscription-api.html)
* [x] Update the way models and are created / managed. View Provider API https://github.com/atom/atom/pull/3587 
* [x] Make a pass through the API and make APIs more consistent / symmetrical 
* [x] New, less confusing command system: https://github.com/atom/atom/pull/3469, https://github.com/atom/atom/pull/3611
* [x] Update the config API https://github.com/atom/atom/issues/3674
* [x] Use disposables everywhere
* [x] Update Project API to handle multiple projects https://github.com/atom/atom/issues/3676
* [x] Panel API similar to the view provider API https://github.com/atom/atom/issues/3680
* [x] Only export core classes. So no jquery, space-pen `View`, etc. 
https://github.com/atom/atom/issues/3672 lays the groundwork
* [x] Remove deprecations from packages
* [x] Update package generator https://github.com/atom/atom/issues/3764
* [x] Enable deprecations for users
* [x] grim is slow. Try to improve https://github.com/atom/atom/issues/3765
* [x] Blog post

### Punting on for now

* [ ] Convert the internal views to HTML custom elements https://github.com/atom/atom/issues/3677 https://github.com/atom/atom/issues/3679
* [ ] Come up with api for creating views in packages https://github.com/atom/atom/issues/3752
* [ ] Use custom tags in tree-view and status-bar.

## Open Issues

See https://github.com/atom/atom/labels/api-freeze-roadmap for a list of open issues

**Comment by benogle** [comment]
Donezo
