### ISSUE TITLE
Split the docs into their own repo

### ISSUE THREAD

**Issue by benogle** [atom/atom#3678]
Let's split the docs out of core. We want to make it easier for people from the community to contribute. The minimum for this to happen is this:

* [ ] Create a docs repo
* [ ] Docs from core in the docs repo
* [ ] Atom.io uses the docs repo
* [ ] Remove docs from core

**Comment by Moter8** [comment]
Bump, can't help without the repo being there or a bit more info.

**Comment by benogle** [comment]
We now have someone internally writing detailed docs. When it is close, we will likely open it up to PRs.

**Comment by thedaniel** [comment]
[this shipped](http://blog.atom.io/2015/03/11/atom-docs.html)
