### ISSUE TITLE
Atom 1.0

### ISSUE THREAD

**Issue by benogle** [atom/atom#3684]
After the API freeze our goal is to implement and fix the very commonly requested features / bugs for a 1.0 release.  

## Tasks

_Note_ these are not in any particular order. 

* Features
  * [ ] Improve Install / Update experience https://github.com/atom/atom/issues/5166
  * [ ] Revisit view system ~~https://github.com/atom/atom/issues/3752~~ https://github.com/atom/atom/issues/5756
  * [ ] Per-project config settings #5168 
* Performance
  * [ ] Startup https://github.com/atom/atom/issues/3673
  * [ ] Large files https://github.com/atom/atom/issues/307
  * [ ] Long lines https://github.com/atom/atom/issues/979 https://github.com/atom/atom/issues/1667
  * [ ] Find and replace https://github.com/atom/find-and-replace/issues/145
* Bugs
  * [ ] Better handling for international keyboards atom/atom-keymap#35 atom/atom-keymap#37
  * [ ] Wrapping foreign / CJK characters #1783 
* API
  * [ ] Remove deprecated APIs #5164 

### Done 

  * [x] Preview pane items https://github.com/atom/atom/issues/3683
  * [x] Autocomplete Next https://github.com/atom/atom/issues/4364
  * [x] Settings UI refresh https://github.com/atom/settings-view/pull/277
  * [x] Windows installer/updater https://github.com/atom/atom/issues/3675
  * [x] Exception user experience (eg. https://github.com/atom/atom/issues/3715) 
  * [x] Grouped undo https://github.com/atom/atom/issues/1606 https://github.com/atom/atom/pull/4071
  * [x] Scoped config settings (PR https://github.com/atom/atom/pull/3718)
  * [x] Support non-UTF-8 encodings https://github.com/atom/atom/issues/1806
  * [x] Multiple folder projects https://github.com/atom/atom/issues/770 https://github.com/atom/tree-view/issues/63
  * [x] Indented soft wrap https://github.com/atom/atom/issues/1125
  * [x] Update default themes https://github.com/atom/atom/issues/5173
  * [x] Typing and cursor movement perf #5163 
  * [x] Tab switching https://github.com/atom/atom/issues/5174
  * [x] Update and clarify the docs https://github.com/atom/atom/issues/3678 https://github.com/atom/atom/issues/3399
  * [x] Services (Inter-package communication) #5165 

## Open Issues

See https://github.com/atom/atom/labels/1.0-roadmap

**Comment by 190N** [comment]
What does "build native themes" mean?

**Comment by nathansobo** [comment]
@190N It means themes that blend in to their respective operating systems. We may remove that item from the 1.0 list.

**Comment by AbeEstrada** [comment]
About "Per-project config settings" doesn't [EditorConfig](https://github.com/sindresorhus/atom-editorconfig) solves this problem?

**Comment by mark-hahn** [comment]
Many add-on packages are superseded by improvements to core.

**Comment by 190n** [comment]
What about automatic updates on Linux? I use Linux, and it's less than ideal to have to remember to check for updates and install them.

**Comment by steelbrain** [comment]
@190n You mean #2956 ? It's already on the roadmap

**Comment by 190n** [comment]
Sorry, I didn't see that.

**Comment by jmm** [comment]
Not sure what the difference is between the checkbox items in the first post and the issues tagged `1.0-roadmap`, but I'd like to nominate all of the "Unable to watch path" issues (like #4849, #3628) to have a higher priority and be on the bugs list here.

**Comment by alexchandel** [comment]
Rather surprising that #4161 didn't make this list, given that crashes exist. Especially since 1.0 milestones are times for userbase expansion, and nothing says **never again** like losing 2 hours of work because something crashed and you didn't save, and your editor doesn't know what recovery or unsaved buffers are.

**Comment by mnquintana** [comment]
For anyone subscribing to this, this is not a *complete* list for what's planned for 1.0, just a high-level overview. Anything with the label `1.0-roadmap` is currently still planned for 1.0 - @alexchandel, the issue you linked to is one of them. In addition, that label is *also* a high-level overview of what's planned for 1.0, and many more issues maybe fixed / implemented yet in the next few weeks, if there's time. Also, 1.0 is not the be-all end-all release - it's not like the pace of development will slow down after 1.0. 1.0 just marks the beginning of the API that will be stable and supported until 2.0; the core team and maintainers will continue fixing bugs and implementing new features after 1.0 is released. So, in conclusion, no one should be concerned if an issue they care about isn't on this list, because it in no way means that it's not going to happen eventually, or even soon.

**Comment by alexchandel** [comment]
@mnquintana Good to hear.

**Comment by robcalcroft** [comment]
Is there a formal release schedule as of yet?

**Comment by stanier** [comment]
https://github.com/atom/atom/issues/5166 is still relevant...

**Comment by kresogalic8** [comment]
Hey guys, just want to say that atom is nice. 

But using it with plugins is really hard. Can u actually work on optimization? Thanks

**Comment by KeitIG** [comment]
That does not really mean something. "What" is really hard ? Performances ? Ease-of-use ? ...
