### ISSUE TITLE
Final API Pass

### ISSUE THREAD

**Issue by benogle** [atom/atom#4242]
Time to do a final API pass. Much of this work will fall out of converting packages in #3966 and #4011.

If you do some of this, post your findings under the following TODO heading.

### TODO

* [x] Deprecate `atom.workspaceView` and remove usage in core, including docs https://github.com/atom/atom/pull/4248
* [x] Remove space-pen-specific views from core docs and suggest [atom-space-pen-views](https://github.com/atom/atom-space-pen-views) instead.
* [x] Create `atom.tooltips` as the old ones no longer work with space-pen split out
* [x] Warn users of new space-pen when they attempt to trigger a command registered via the command registry 
* [x] Fix references to spacepen 3, use spacepen 4
* [x] Warn users when they `subscribeToCommand` on space-pen view
* [x] Warn users when they subscribe to commands via `on` with new space-pen?
* [x] Merge and release SpacePen 4 warnings PR @nathansobo 
* [x] Fix prose docs. Make sure they dont reference old APIs @nathansobo 
* [x] Add `.panes` -> `atom-pane-container` to selector linter
* [x] Add `.pane-row` / `.pane-column` -> `atom-pane-axis` with `.horizontal` or `.vertical` class
* [x] Remove Deprecations from core https://github.com/atom/atom/pull/4315
* [x] Need an alternative to workspaceView's `window:update-available` on atom, and other non-command ipc events. See https://github.com/atom/atom/blob/master/src/window-event-handler.coffee#L17 and https://github.com/atom/atom/blob/1406fbfe03232144c245fce2783abd7f818ba854/spec/atom-spec.coffee#L36 @nathansobo 
* [x] Fix `atom.commands.add` docs. They have 2 separate arg lists. Can merge? @benogle (likely update atomdoc) https://github.com/github/atom.io/pull/759
* [x] Update the styleguide to use new markup
* [x] Fix package generator. Make sure it doesnt use old APIs @benogle https://github.com/atom/apm/pull/225 and https://github.com/atom/space-pen-example-templates
* [x] Examples in tooltip manager api docs @benogle
* [x] What's up with the `.pane-item` selector?
* [x] Warn when people access deprecated views via the `$::view` method.
* [x] Add exceptions for outdated `::afterAttach` and `::beforeRemove` lifecycle hooks on new SpacePen views
