### ISSUE TITLE
Remove deprecations from bundled packages, round 2

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#4853]
We added a couple more deprecations after the first pass, necessitating a second. This one should be quicker.

* [x] atom-dark-syntax
* [x] atom-dark-ui
* [x] atom-light-syntax
* [x] atom-light-ui
* [x] base16-tomorrow-dark-theme
* [x] base16-tomorrow-light-theme
* [x] solarized-dark-syntax
* [x] solarized-light-syntax
* [x] archive-view
* [x] autocomplete
* [x] autoflow
* [x] autosave
* [x] background-tips
* [x] bookmarks
* [x] bracket-matcher
* [x] command-palette
* [x] deprecation-cop
* [x] dev-live-reload
* [x] encoding-selector
* [x] exception-reporting
* [x] find-and-replace
* [x] fuzzy-finder
* [x] git-diff
* [x] go-to-line
* [x] grammar-selector
* [x] image-view
* [x] incompatible-packages
* [x] keybinding-resolver
* [x] link
* [x] markdown-preview
* [x] metrics
* [x] notifications
* [x] open-on-github
* [x] package-generator
* [x] release-notes
* [x] settings-view https://github.com/atom/settings-view/pull/311
* [x] snippets
* [x] spell-check
* [x] status-bar
* [x] styleguide
* [x] symbols-view
* [x] tabs
* [x] timecop
* [x] tree-view
* [x] update-package-dependencies
* [x] welcome
* [x] whitespace
* [x] wrap-guide
* [x] language-c
* [x] language-clojure
* [x] language-coffee-script
* [x] language-css
* [x] language-gfm
* [x] language-git
* [x] language-go
* [x] language-html
* [x] language-hyperlink
* [x] language-java
* [x] language-javascript
* [x] language-json
* [x] language-less
* [x] language-make
* [x] language-mustache
* [x] language-objective-c
* [x] language-perl
* [x] language-php
* [x] language-property-list
* [x] language-python
* [x] language-ruby
* [x] language-ruby-on-rails
* [x] language-sass
* [x] language-shellscript
* [x] language-source
* [x] language-sql
* [x] language-text
* [x] language-todo
* [x] language-toml
* [x] language-xml
* [x] language-yaml
