### ISSUE TITLE
Deprecate old tab selectors

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#5020]
Add deprecations in [atom-selector-linter](http://github.com/atom/atom-selector-linter). I believe the required updates are:
* [ ] `.tab-bar` -> `atom-tab-bar`
* [ ] `.tab` -> `atom-tab`

/cc @benogle. Are these right?

**Comment by benogle** [comment]
Almost:

* [ ] `.tab-bar` -> `tabs-bar`
* [ ] `.tab` -> `tabs-tab`
* [ ] `.tree-view` -> `tree-view .list-tree` (tree view is now the root, and it was not before, the resizer was the root. I was on the fence, but leaning toward it encompassing all the tree-view nodes.)

**Comment by benogle** [comment]
Removed the tree-view selector items. We decided to punt on atom/tree-view#324
