### ISSUE TITLE
Remove deprecations from bundled packages, round 3

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#5042]
This should be the final pass.

* [x] atom-dark-syntax
* [x] atom-dark-ui
* [x] atom-light-syntax
* [x] atom-light-ui
* [x] base16-tomorrow-dark-theme
* [x] base16-tomorrow-light-theme
* [x] solarized-dark-syntax
* [x] solarized-light-syntax
* [x] archive-view
* [x] autocomplete
* [x] autoflow
* [x] autosave
* [x] background-tips
* [x] bookmarks
* [x] bracket-matcher
* [x] command-palette
* [x] deprecation-cop
* [x] dev-live-reload
* [x] encoding-selector
* [x] exception-reporting
* [x] find-and-replace
* [x] fuzzy-finder
* [x] git-diff
* [x] go-to-line
* [x] grammar-selector
* [x] image-view
* [x] incompatible-packages
* [x] keybinding-resolver
* [x] link
* [x] markdown-preview
* [x] metrics
* [x] notifications
* [x] open-on-github
* [x] package-generator
* [x] release-notes
* [x] settings-view
* [x] snippets
* [x] spell-check
* [x] status-bar
* [x] styleguide
* [x] symbols-view
* [x] tabs
* [x] timecop
* [x] tree-view
* [x] update-package-dependencies
* [x] welcome
* [x] whitespace
* [x] wrap-guide
