### ISSUE TITLE
Tracking Issue: Decouple Services API versioning from package versioning

### ISSUE THREAD

**Issue by jlord** [atom/atom#5726]
Changing the `status-bar` Services API versioning:

- [x] Change `status-bar` Services API current version to `1.0.0` https://github.com/atom/status-bar/pull/57
 - [x] Create a legacy method to depreciate with Grim
 - [x] fix branch spec bug https://github.com/atom/status-bar/pull/58
- [x] Update atom/atom with new `status-bar` version https://github.com/atom/atom/pull/5755
- [x] Update consuming package to use `^1.0.0`
 - [x] `grammar-selector` https://github.com/atom/grammar-selector/pull/17
 - [x] `encoding-selector` https://github.com/atom/encoding-selector/pull/20
 - [x] `incompatible-packages` https://github.com/atom/incompatible-packages/pull/6
 - [x] `release-notes` https://github.com/atom/release-notes/pull/34
 - [x] `vim-mode` https://github.com/atom/vim-mode/pull/542
- [x] After Atom 0.187 publish minor on packages
  - [x] `vim-mode` publish
  - [x] `release-notes` publish
  - [x] `incompatible-packages` publish
  - [x] `encoding-selector` publish 
  - [x] `grammar-selector` publish
- [x] Update atom/atom to use new versions of each :arrow_heading_up: for 0.188 https://github.com/atom/atom/pull/5926
- [x] After 0.188 add depreciation back to `status-bar` https://github.com/atom/status-bar/pull/63
 - [x] `status-bar` publish minor
- [x] Update atom/atom with new `status-bar` version https://github.com/atom/atom/pull/6084
- [x] Blog post! https://github.com/atom/blog.atom.io/pull/90

**Comment by kevinsawicki** [comment]
:fireworks:
