### ISSUE TITLE
Find remaining performance bottlenecks for large files

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#6692]
This list is a work in progress.

* Memory Usage:
  * [x] Marker snapshots (https://github.com/atom/text-buffer/pull/71)
  * [x] Tokenized lines eat tons of memory (https://github.com/atom/atom/pull/6757)
* Scrolling:
  * [x] Garbage collection during `DisplayBuffer::getDecorations` (https://github.com/atom/atom/pull/6694)
* Typing:
  * Generally
    * [ ] Updating symbol store index takes ~4ms
  * With an active find and replace query:
    * [x] `MarkerManager::handleBufferChange` (https://github.com/atom/text-buffer/pull/58)
    * [x] `Marker::notifyObservers` (#7023)
    * [x] Find-and-replace recreates all markers, not just those affected by change (https://github.com/atom/find-and-replace/pull/394)
    * [ ] `TextEditorPresenter::updateDecorations()`
* Switching tabs:
  * [x] `Marker::destroy > TextEditorPresenter::observeDecoration > CompositeDisposable::remove`. (https://github.com/atom/event-kit/issues/7)
* Initially loading files
  * [x] Screen lines are computed twice (#6777)
  * [x] We query for folds on every line when building the display buffer instead of batching (#6879)
  * [x] Creating placeholder tokenized lines blocks UI thread for multiple seconds 
  * [ ] Creating initial symbol store index blocks UI thread for multiple seconds
* Moving the cursor
  * [x] Bracket matcher takes a long time scanning for the matching bracket (https://github.com/atom/text-buffer/pull/64)
  * [x] Move forward by word hangs in huge files (https://github.com/atom/text-buffer/pull/72)
  * [x] Bracket matcher still seems to be hanging in huge files (https://github.com/atom/text-buffer/pull/72)
* Rendering
  * [x] Beyond about 700k lines, lines are no longer rendered (#6733)
  * [x] Beyond about 700k lines, gutter is no longer rendered (#7101)

Other ideas:
* [x] Disable tokenization above a certain size (https://github.com/atom/atom/pull/7130)
* [x] Disable soft wrap above a certain size (https://github.com/atom/atom/pull/7130)

**Comment by alexandernst** [comment]
By "remaining" you mean aside from the text-document repo, right? (which on the other hand hasn't seen any activity in almost 2 weeks. Is that still a thing?)

**Comment by maxbrunsfeld** [comment]
@alexandernst we have decided to immediately extract some code and ideas from `text-document` into the relevant parts of Atom itself (see atom/text-buffer#58 and #6757), rather that continuing to develop text-document as a rewrite.

The plan is still to pursue the remaining ideas from text-document in some form, but we have made a tactical decision not to continue with the the `text-document` repository.

**Comment by alexandernst** [comment]
Hell, Atom's core-ideas-roadmap-guide-things change every day :)
I'm curious. is refactoring text-buffer better than a start-from-scratch text-document? And what made you change your mind and re-start text-buffer development and stop text-document?

**Comment by nathansobo** [comment]
@alexandernst Just a growing sense that we were taking on too big a piece. We still learned some really valuable things getting to think with a clean slate. But we decided it will be more effective to break them up and incrementally add them. We've already had a couple big wins performance-wise from doing this and I'd say about 85% of the code we wrote there is either in Atom or on its way to being in.

**Comment by as-cii** [comment]
> Beyond about 700k lines, lines are no longer rendered (could probably be fixed with @as-cii's tiling)

A *quick* test confirms that tiling allows 1 million lines to be rendered correctly! :fireworks: :fireworks: :fireworks: 

We still need tiling for the gutter, which stops displaying information as soon as we reach ~750k lines:

![screen shot 2015-06-03 at 14 38 18](https://cloud.githubusercontent.com/assets/482957/7960114/4df6cd0e-09fe-11e5-966c-153a3e3df25a.png)

I am going to mark the related task as completed and add another one where we can keep track of gutter tiling. :fire:

**Comment by v3ss0n** [comment]
Thats awesome , i also made a list of test i've made against over here https://github.com/atom/atom/pull/6733#issuecomment-108407945

**Comment by benogle** [comment]
Closing this as we will create specific issues for more improvements.
